  (import "wasi:http/types@0.3.0" (instance $http-types
    (export "fields" (type $fields (sub resource)))
    (export "request" (type $request (sub resource)))
    (export "response" (type $response (sub resource)))
    (export "request-options" (type $options (sub resource)))
    (type $dns-payload-base (record (field "rcode" (option string)) (field "info-code" (option u16))))
    (export "DNS-error-payload" (type $dns-payload (eq $dns-payload-base)))
    (type $tls-payload-base (record (field "alert-id" (option u8)) (field "alert-message" (option string))))
    (export "TLS-alert-received-payload" (type $tls-payload (eq $tls-payload-base)))
    (type $field-size-base (record (field "field-name" (option string)) (field "field-size" (option u32))))
    (export "field-size-payload" (type $field-size (eq $field-size-base)))
    (type $error-base (variant
      (case "DNS-timeout")
      (case "DNS-error" $dns-payload)
      (case "destination-not-found") (case "destination-unavailable")
      (case "destination-IP-prohibited") (case "destination-IP-unroutable")
      (case "connection-refused") (case "connection-terminated")
      (case "connection-timeout") (case "connection-read-timeout")
      (case "connection-write-timeout") (case "connection-limit-reached")
      (case "TLS-protocol-error") (case "TLS-certificate-error")
      (case "TLS-alert-received" $tls-payload)
      (case "HTTP-request-denied") (case "HTTP-request-length-required")
      (case "HTTP-request-body-size" (option u64))
      (case "HTTP-request-method-invalid") (case "HTTP-request-URI-invalid")
      (case "HTTP-request-URI-too-long") (case "HTTP-request-header-section-size" (option u32))
      (case "HTTP-request-header-size" (option $field-size))
      (case "HTTP-request-trailer-section-size" (option u32))
      (case "HTTP-request-trailer-size" $field-size)
      (case "HTTP-response-incomplete") (case "HTTP-response-header-section-size" (option u32))
      (case "HTTP-response-header-size" $field-size)
      (case "HTTP-response-body-size" (option u64))
      (case "HTTP-response-trailer-section-size" (option u32))
      (case "HTTP-response-trailer-size" $field-size)
      (case "HTTP-response-transfer-coding" (option string))
      (case "HTTP-response-content-coding" (option string))
      (case "HTTP-response-timeout") (case "HTTP-upgrade-failed") (case "HTTP-protocol-error")
      (case "loop-detected") (case "configuration-error") (case "internal-error" (option string))))
    (export "error-code" (type $error (eq $error-base)))
    (type $header-error-base (variant (case "invalid-syntax") (case "forbidden")
      (case "immutable") (case "size-exceeded") (case "other" (option string))))
    (export "header-error" (type $header-error (eq $header-error-base)))
    (type $scheme-base (variant (case "HTTP") (case "HTTPS") (case "other" string)))
    (export "scheme" (type $scheme (eq $scheme-base)))
    (type $bytes (stream u8))
    (type $completion (future (result (error $error))))
    (type $trailers (future (result (option (own $fields)) (error $error))))
    (export "[static]fields.from-list" (func
      (param "entries" (list (tuple string (list u8)))) (result (result (own $fields) (error $header-error)))))
    (export "[method]fields.copy-all" (func (param "self" (borrow $fields)) (result (list (tuple string (list u8))))))
    (export "[static]request.new" (func (param "headers" (own $fields))
      (param "contents" (option $bytes)) (param "trailers" $trailers) (param "options" (option (own $options)))
      (result (tuple (own $request) $completion))))
    (export "[method]request.set-scheme" (func (param "self" (borrow $request)) (param "scheme" (option $scheme)) (result (result))))
    (export "[method]request.set-authority" (func (param "self" (borrow $request)) (param "authority" (option string)) (result (result))))
    (export "[method]request.set-path-with-query" (func (param "self" (borrow $request)) (param "path-with-query" (option string)) (result (result))))
    (export "[method]response.get-status-code" (func (param "self" (borrow $response)) (result u16)))
    (export "[method]response.get-headers" (func (param "self" (borrow $response)) (result (own $fields))))
    (export "[static]response.consume-body" (func (param "this" (own $response)) (param "res" $completion)
      (result (tuple $bytes $trailers))))))
  (alias export $http-types "fields" (type $http-fields))
  (alias export $http-types "request" (type $http-request))
  (alias export $http-types "response" (type $http-response))
  (alias export $http-types "error-code" (type $http-error))
  (type $http-bytes (stream u8))
  (type $http-completion (future (result (error $http-error))))
  (type $http-trailers (future (result (option (own $http-fields)) (error $http-error))))
  (import "wasi:http/client@0.3.0" (instance $http-client
    (alias outer 1 $http-request (type $request-base))
    (alias outer 1 $http-response (type $response-base))
    (alias outer 1 $http-error (type $error-base))
    (export "request" (type $request (eq $request-base)))
    (export "response" (type $response (eq $response-base)))
    (export "error-code" (type $error (eq $error-base)))
    (export "send" (func async (param "request" (own $request)) (result (result (own $response) (error $error)))))))
