  (import "host" "read-buffered" (func $read-buffered (param i32 i32) (result i32 i32 i32)))
  (import "host" "realloc" (func $realloc (param i32 i32 i32 i32) (result i32)))
  (import "host" "frame-new" (func $frame-new (param i32) (result i32)))
  (import "host" "frame-drop" (func $frame-drop (param i32)))

  (func $finish-write (param $writer i32) (param $status i32) (param $scratch i32)
    (local $set i32)
    (if (i32.eq (local.get $status) (i32.const -1)) (then
      (local.set $set (call $new-set))
      (call $join (local.get $writer) (local.get $set))
      (if (i32.ne (call $wait (local.get $set) (local.get $scratch)) (i32.const 5)) (then unreachable))
      (if (i32.ne (i32.load (local.get $scratch)) (local.get $writer)) (then unreachable))
      (local.set $status (i32.load offset=4 (local.get $scratch)))
      (call $join (local.get $writer) (i32.const 0))
      (call $drop-set (local.get $set))))
    (if (i32.gt_u (local.get $status) (i32.const 1)) (then unreachable)))

  ;; Canonical request inputs; output is status, header-list pointer/count, body pointer/length.
  ;; HTTP errors are 100 + WIT discriminant, header errors 200 + discriminant;
  ;; invalid request metadata is 12, and response limit overflow is 8.
  (func (export "http.get") (param $scheme i32) (param $authority i32) (param $authority-length i32)
    (param $path i32) (param $path-length i32) (param $fields i32) (param $field-count i32)
    (param $limit i32) (param $out i32) (result i32)
    (local $frame i32) (local $scratch i32) (local $request i32) (local $request-done i32)
    (local $trailers i64) (local $trailer-writer i32) (local $trailer-status i32)
    (local $response i32) (local $headers i32) (local $has-response i32) (local $ack i64) (local $ack-writer i32)
    (local $reader i32) (local $response-done i32) (local $error i32) (local $data i32) (local $length i32)
    (local.set $frame (call $frame-new (i32.const 2)))
    (local.set $scratch (call $realloc (i32.const 0) (i32.const 0) (i32.const 8) (i32.const 256)))
    (i32.store offset=12 (local.get $frame) (local.get $scratch))
    (memory.fill (local.get $scratch) (i32.const 0) (i32.const 256))
    (block $done
      (call $fields (local.get $fields) (local.get $field-count) (local.get $scratch))
      (if (i32.load8_u (local.get $scratch)) (then
        (local.set $error (i32.add (i32.const 200) (i32.load8_u offset=4 (local.get $scratch)))) (br $done)))
      (local.set $trailers (call $new-trailers))
      (local.set $trailer-writer (i32.wrap_i64 (i64.shr_u (local.get $trailers) (i64.const 32))))
      (call $request (i32.load offset=4 (local.get $scratch)) (i32.const 0) (i32.const 0)
        (i32.wrap_i64 (local.get $trailers)) (i32.const 0) (i32.const 0) (local.get $scratch))
      (local.set $request (i32.load (local.get $scratch)))
      (local.set $request-done (i32.load offset=4 (local.get $scratch)))
      (if (i32.or
        (call $scheme (local.get $request) (i32.const 1) (local.get $scheme) (i32.const 0) (i32.const 0))
        (i32.or (call $authority (local.get $request) (i32.const 1) (local.get $authority) (local.get $authority-length))
          (call $path (local.get $request) (i32.const 1) (local.get $path) (local.get $path-length)))) (then
        (call $drop-request (local.get $request))
        (call $drop-completion-reader (local.get $request-done))
        (call $finish-write (local.get $trailer-writer)
          (call $write-trailers (local.get $trailer-writer) (i32.add (local.get $scratch) (i32.const 64)))
          (i32.add (local.get $scratch) (i32.const 192)))
        (call $drop-trailers-writer (local.get $trailer-writer))
        (local.set $error (i32.const 12)) (br $done)))
      (local.set $trailer-status (call $write-trailers (local.get $trailer-writer) (i32.add (local.get $scratch) (i32.const 64))))
      (call $send (local.get $request) (local.get $scratch))
      (if (i32.load8_u (local.get $scratch))
        (then (local.set $error (i32.add (i32.const 100) (i32.load8_u offset=8 (local.get $scratch)))))
        (else
          (local.set $has-response (i32.const 1))
          (local.set $response (i32.load offset=8 (local.get $scratch)))
          (i32.store (local.get $out) (call $status (local.get $response)))
          (local.set $headers (call $headers (local.get $response)))
          (local.set $ack (call $new-completion))
          (local.set $ack-writer (i32.wrap_i64 (i64.shr_u (local.get $ack) (i64.const 32))))
          (call $consume (local.get $response) (i32.wrap_i64 (local.get $ack)) (local.get $scratch))
          (local.set $reader (i32.load (local.get $scratch)))
          (local.set $response-done (i32.load offset=4 (local.get $scratch)))
          (call $read-buffered (local.get $reader) (local.get $limit))
          local.set $length local.set $data local.set $error
          (i32.store offset=16 (local.get $frame) (local.get $data))
          (local.set $error (i32.mul (local.get $error) (i32.const 8)))
          (call $drop-reader (local.get $reader))
          (if (call $read-trailers (local.get $response-done) (local.get $scratch)) (then unreachable))
          (call $drop-trailers-reader (local.get $response-done))
          (if (i32.load8_u (local.get $scratch))
            (then (if (i32.eqz (local.get $error)) (then
              (local.set $error (i32.add (i32.const 100) (i32.load8_u offset=8 (local.get $scratch)))))))
            (else (if (i32.load8_u offset=8 (local.get $scratch)) (then (call $drop-fields (i32.load offset=12 (local.get $scratch)))))))
          (if (local.get $error) (then
            (i32.store offset=128 (local.get $scratch) (i32.const 1))
            (i32.store offset=136 (local.get $scratch) (i32.const 25))))
          (call $finish-write (local.get $ack-writer)
            (call $write-completion (local.get $ack-writer) (i32.add (local.get $scratch) (i32.const 128)))
            (i32.add (local.get $scratch) (i32.const 192)))
          (call $drop-completion-writer (local.get $ack-writer))
          (i32.store offset=12 (local.get $out) (local.get $data))
          (i32.store offset=16 (local.get $out) (local.get $length))))
      (if (call $read-completion (local.get $request-done) (local.get $scratch)) (then unreachable))
      (call $drop-completion-reader (local.get $request-done))
      (if (i32.and (i32.eqz (local.get $error)) (i32.load8_u (local.get $scratch))) (then
        (local.set $error (i32.add (i32.const 100) (i32.load8_u offset=8 (local.get $scratch))))))
      (call $finish-write (local.get $trailer-writer) (local.get $trailer-status) (i32.add (local.get $scratch) (i32.const 192)))
      (call $drop-trailers-writer (local.get $trailer-writer))
      (if (local.get $has-response) (then
        (call $copy-fields (local.get $headers) (i32.add (local.get $out) (i32.const 4)))
        (call $drop-fields (local.get $headers)))))
    (call $frame-drop (local.get $frame))
    (local.get $error))
