(module
  (import "host" "get" (func $get (param i32 i32 i32 i32 i32 i32 i32 i32 i32) (result i32)))
  (import "host" "realloc" (func $realloc (param i32 i32 i32 i32) (result i32)))
  (import "host" "frame-new" (func $frame-new (param i32) (result i32)))
  (import "host" "frame-drop" (func $frame-drop (param i32)))
  (import "host" "compare" (func $compare (param i32 i32) (result i32)))
  (import "host" "string-lift" (func $string-lift (param i32 i32) (result i32)))
  (import "host" "bytes-lift" (func $bytes-lift (param i32 i32) (result i32)))
  (memory 1)
  ;; Response: status, canonical header-list pointer/count, body view, reserved.
  (func (export "get") (param $scheme i32) (param $authority i32) (param $path i32)
    (param $headers i32) (param $limit f64) (result i32 f64)
    (local $frame i32) (local $entry i32) (local $count i32) (local $fields i32)
    (local $target i32) (local $key i32) (local $value i32) (local $response i32) (local $error i32) (local $secure i32)
    (if (i32.eqz (i32.and (f64.eq (local.get $limit) (f64.trunc (local.get $limit)))
      (i32.and (f64.ge (local.get $limit) (f64.const 0)) (f64.le (local.get $limit) (f64.const 4294967295)))))
      (then (return (i32.const 1) (f64.const 12))))
    (if (call $compare (local.get $scheme) (i32.const HTTP_TEXT)) (then
      (if (call $compare (local.get $scheme) (i32.const HTTPS_TEXT)) (then (return (i32.const 1) (f64.const 12))))
      (local.set $secure (i32.const 1))))
    (local.set $entry (i32.load (local.get $headers)))
    (block $counted (loop $counting
      (br_if $counted (i32.eqz (local.get $entry)))
      (if (i32.ne (i32.load offset=8 (local.get $entry)) (i32.const 4)) (then (return (i32.const 1) (f64.const 12))))
      (local.set $count (i32.add (local.get $count) (i32.const 1)))
      (if (i32.gt_u (local.get $count) (i32.const 268435455)) (then unreachable))
      (local.set $entry (i32.load (local.get $entry))) (br $counting)))
    (local.set $frame (call $frame-new (i32.const 6)))
    (i32.store offset=12 (local.get $frame) (local.get $scheme))
    (i32.store offset=16 (local.get $frame) (local.get $authority))
    (i32.store offset=20 (local.get $frame) (local.get $path))
    (i32.store offset=24 (local.get $frame) (local.get $headers))
    (local.set $fields (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.mul (local.get $count) (i32.const 16))))
    (i32.store offset=28 (local.get $frame) (local.get $fields))
    (local.set $target (local.get $fields))
    (local.set $entry (i32.load (local.get $headers)))
    (block $copied (loop $copy
      (br_if $copied (i32.eqz (local.get $entry)))
      (local.set $key (i32.load offset=4 (local.get $entry)))
      (local.set $value (i32.trunc_f64_u (f64.load offset=16 (local.get $entry))))
      (memory.copy (local.get $target) (local.get $key) (i32.const 8))
      (memory.copy (i32.add (local.get $target) (i32.const 8)) (local.get $value) (i32.const 8))
      (local.set $target (i32.add (local.get $target) (i32.const 16)))
      (local.set $entry (i32.load (local.get $entry))) (br $copy)))
    (local.set $response (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 20)))
    (memory.fill (local.get $response) (i32.const 0) (i32.const 20))
    (i32.store offset=16 (i32.load (i32.sub (local.get $response) (i32.const 4))) (i32.const 13))
    (i32.store offset=32 (local.get $frame) (local.get $response))
    (local.set $error (call $get (local.get $secure) (i32.load (local.get $authority)) (i32.load offset=4 (local.get $authority))
      (i32.load (local.get $path)) (i32.load offset=4 (local.get $path)) (local.get $fields) (local.get $count)
      (i32.trunc_f64_u (local.get $limit)) (local.get $response)))
    (if (i32.eqz (local.get $error)) (then
      (i32.store offset=12 (local.get $response) (call $bytes-lift (i32.load offset=12 (local.get $response)) (i32.load offset=16 (local.get $response))))))
    (call $frame-drop (local.get $frame))
    (if (local.get $error) (then (return (i32.const 1) (f64.convert_i32_u (local.get $error)))))
    (i32.const 0) (f64.convert_i32_u (local.get $response)))

  (func (export "header") (param $response i32) (param $index f64) (param $bytes i32) (result i32 f64)
    (local $entry i32) (local $descriptor i32)
    (if (i32.eqz (i32.and (f64.eq (local.get $index) (f64.trunc (local.get $index)))
      (i32.and (f64.ge (local.get $index) (f64.const 0)) (f64.lt (local.get $index) (f64.convert_i32_u (i32.load offset=8 (local.get $response)))))))
      (then (return (i32.const 1) (f64.const 12))))
    (local.set $entry (i32.add (i32.load offset=4 (local.get $response)) (i32.mul (i32.trunc_f64_u (local.get $index)) (i32.const 16))))
    (local.set $descriptor (if (result i32) (local.get $bytes)
      (then (call $bytes-lift (i32.load offset=8 (local.get $entry)) (i32.load offset=12 (local.get $entry))))
      (else (call $string-lift (i32.load (local.get $entry)) (i32.load offset=4 (local.get $entry))))))
    (i32.const 0) (f64.convert_i32_u (local.get $descriptor))))
