//! Allocation lookup keeps interior-pointer tracing on the existing guest heap.
//! During collection, header word 24 skips 32 blocks in the ordered allocation
//! list. Collection builds these links once and invalidates them before coalescing.

use crate::waffle_backend::runtime::builder::{self, Builder};
use anyhow::Result;
use waffle::{Func, Memory, Module, Operator, Type};

pub(super) fn emit(module: &mut Module<'static>, memory: Memory) -> Result<(Func, Func)> {
    use Type::I32;
    let find = builder::declare(module, "heap.find", &[I32], &[I32]);
    let index = builder::declare(module, "heap.index", &[], &[]);
    let mut b = Builder::new(module, find, memory);
    let pointer = b.param(0);
    let head_address = b.integer(36);
    let head = b.load(head_address, 0, I32);
    let missing = b.body.add_block();
    let bounds = b.body.add_block();
    b.branch(head, bounds, missing);
    b.block = bounds;
    let tail_address = b.integer(40);
    let tail = b.load(tail_address, 0, I32);
    let span = b.load(tail, 4, I32);
    let end = b.op(Operator::I32Add, &[tail, span], I32);
    let low = b.op(Operator::I32GeU, &[pointer, head], I32);
    let high = b.op(Operator::I32LtU, &[pointer, end], I32);
    let valid = b.op(Operator::I32And, &[low, high], I32);
    let start = b.body.add_block();
    b.branch(valid, start, missing);
    b.block = start;
    let next = b.body.add_block();
    let block = b.body.add_blockparam(next, I32);
    let check = b.body.add_block();
    b.jump(next, &[head]);
    b.block = next;
    b.branch(block, check, missing);
    b.block = check;
    let live = b.load(block, 16, I32);
    let free = b.integer(u32::MAX);
    let live = b.op(Operator::I32Ne, &[live, free], I32);
    let offset = b.load(block, 8, I32);
    let base = b.op(Operator::I32Add, &[block, offset], I32);
    let size = b.load(block, 12, I32);
    let end = b.op(Operator::I32Add, &[base, size], I32);
    let low = b.op(Operator::I32GeU, &[pointer, base], I32);
    let high = b.op(Operator::I32LtU, &[pointer, end], I32);
    let contains = b.op(Operator::I32And, &[low, high], I32);
    let contains = b.op(Operator::I32And, &[live, contains], I32);
    let found = b.body.add_block();
    let following = b.body.add_block();
    b.branch(contains, found, following);
    b.block = found;
    b.ret(&[block]);
    b.block = following;
    let indexed_address = b.integer(96);
    let indexed = b.load(indexed_address, 0, I32);
    let skip = b.body.add_block();
    let linear = b.body.add_block();
    b.branch(indexed, skip, linear);
    b.block = skip;
    let target = b.load(block, 24, I32);
    let can_skip = b.op(Operator::I32GeU, &[pointer, target], I32);
    let present = b.op(Operator::I32Eqz, &[target], I32);
    let present = b.op(Operator::I32Eqz, &[present], I32);
    let can_skip = b.op(Operator::I32And, &[can_skip, present], I32);
    let advance = b.body.add_block();
    b.branch(can_skip, advance, linear);
    b.block = advance;
    b.jump(next, &[target]);
    b.block = linear;
    let following = b.load(block, 0, I32);
    b.jump(next, &[following]);
    b.block = missing;
    let zero = b.integer(0);
    b.ret(&[zero]);
    b.finish(module, find)?;

    let mut b = Builder::new(module, index, memory);
    let head_address = b.integer(36);
    let head = b.load(head_address, 0, I32);
    let zero = b.integer(0);
    let one = b.integer(1);
    let width = b.integer(32);
    let lead = b.body.add_block();
    let leading = b.body.add_blockparam(lead, I32);
    let count = b.body.add_blockparam(lead, I32);
    let advance = b.body.add_block();
    let ready = b.body.add_block();
    b.jump(lead, &[head, zero]);
    b.block = lead;
    let more = b.op(Operator::I32LtU, &[count, width], I32);
    let present = b.op(Operator::I32Eqz, &[leading], I32);
    let present = b.op(Operator::I32Eqz, &[present], I32);
    let more = b.op(Operator::I32And, &[more, present], I32);
    b.branch(more, advance, ready);
    b.block = advance;
    let following = b.load(leading, 0, I32);
    let count = b.op(Operator::I32Add, &[count, one], I32);
    b.jump(lead, &[following, count]);
    b.block = ready;
    let next = b.body.add_block();
    let block = b.body.add_blockparam(next, I32);
    let ahead = b.body.add_blockparam(next, I32);
    let write = b.body.add_block();
    let done = b.body.add_block();
    b.jump(next, &[head, leading]);
    b.block = next;
    b.branch(block, write, done);
    b.block = write;
    b.store(block, 24, ahead, I32);
    let following = b.load(block, 0, I32);
    let shift = b.body.add_block();
    let tail = b.body.add_block();
    b.branch(ahead, shift, tail);
    b.block = shift;
    let ahead = b.load(ahead, 0, I32);
    b.jump(next, &[following, ahead]);
    b.block = tail;
    b.jump(next, &[following, zero]);
    b.block = done;
    let indexed_address = b.integer(96);
    b.store(indexed_address, 0, one, I32);
    b.ret(&[]);
    b.finish(module, index)?;
    Ok((find, index))
}
