(type $bytes (stream u8))
(core module $stream-memory (memory (export "memory") 1 1))
(core instance $stream-memory (instantiate $stream-memory))
(core func $stream-read (canon stream.read $bytes (memory (core memory $stream-memory "memory"))))
(core func $stream-drop (canon stream.drop-readable $bytes))
(core module $stream-io
  (import "native" "memory" (memory 1 1))
  (import "native" "read" (func $read (param i32 i32 i32) (result i32)))
  (import "native" "drop" (func $drop (param i32)))
  ;; Header: chunk length, EOF, active flag, owning stream. Bytes begin at 16.
  (func $check-owner (param $stream i32)
    (if (i32.eqz (i32.load (i32.const 8))) (then unreachable))
    (if (i32.ne (local.get $stream) (i32.load (i32.const 12))) (then unreachable)))
  (func (export "start") (param $stream i32)
    (if (i32.load (i32.const 8)) (then unreachable))
    (i32.store (i32.const 8) (i32.const 1))
    (i32.store (i32.const 12) (local.get $stream))
    (i32.store (i32.const 0) (i32.const 0))
    (i32.store (i32.const 4) (i32.const 0)))
  (func (export "drop") (param $stream i32)
    (call $check-owner (local.get $stream))
    (call $drop (local.get $stream))
    (i32.store (i32.const 8) (i32.const 0))
    (i32.store (i32.const 0) (i32.const 0)))
  (func (export "read-chunk") (param $stream i32) (result f64)
    (local $status i32) (local $length i32)
    (call $check-owner (local.get $stream))
    (if (i32.load (i32.const 4))
      (then (i32.store (i32.const 0) (i32.const 0)) (return (f64.const 0))))
    (loop $read-again
      (local.set $status (call $read (local.get $stream) (i32.const 16) (i32.const 8192)))
      ;; Synchronous canonical reads suspend; BLOCKED/CANCELLED cannot be returned.
      (if (i32.gt_u (i32.and (local.get $status) (i32.const 15)) (i32.const 1)) (then unreachable))
      (local.set $length (i32.shr_u (local.get $status) (i32.const 4)))
      (if (i32.gt_u (local.get $length) (i32.const 8192)) (then unreachable))
      (i32.store (i32.const 0) (local.get $length))
      (i32.store (i32.const 4) (i32.and (local.get $status) (i32.const 1)))
      (br_if $read-again (i32.and (i32.eqz (local.get $length)) (i32.eqz (i32.load (i32.const 4))))))
    (f64.convert_i32_u (local.get $length)))
  (func (export "byte-at") (param $index f64) (result f64)
    (local $integer i32)
    (if (i32.eqz (i32.load (i32.const 8))) (then unreachable))
    (if (f64.ne (local.get $index) (f64.trunc (local.get $index))) (then unreachable))
    (local.set $integer (i32.trunc_f64_u (local.get $index)))
    (if (i32.ge_u (local.get $integer) (i32.load (i32.const 0))) (then unreachable))
    (f64.convert_i32_u (i32.load8_u (i32.add (i32.const 16) (local.get $integer))))))
(core instance $stream-io (instantiate $stream-io
  (with "native" (instance
    (export "memory" (memory $stream-memory "memory"))
    (export "read" (func $stream-read)) (export "drop" (func $stream-drop))))))
