(module
  (import "host" "memory" (memory 1))
  (import "host" "read" (func $read (param i32 i32 i32) (result i32)))
  (import "host" "drop" (func $drop (param i32)))
  (import "host" "realloc" (func $realloc (param i32 i32 i32 i32) (result i32)))
  (import "host" "frame-new" (func $frame-new (param i32) (result i32)))
  (import "host" "frame-drop" (func $frame-drop (param i32)))
  ;; Invocation header: active 48, stream 52, chunk buffer 56, chunk length 60,
  ;; EOF 64, buffer root frame 68. The chunk buffer is allocated only on demand.
  (func $check-owner (param $stream i32)
    (if (i32.eqz (i32.load (i32.const 48))) (then unreachable))
    (if (i32.ne (local.get $stream) (i32.load (i32.const 52))) (then unreachable)))
  (func (export "stream.start") (param $stream i32)
    (if (i32.load (i32.const 48)) (then unreachable))
    (i32.store (i32.const 48) (i32.const 1))
    (i32.store (i32.const 52) (local.get $stream))
    (i32.store (i32.const 56) (i32.const 0))
    (i32.store (i32.const 60) (i32.const 0))
    (i32.store (i32.const 64) (i32.const 0))
    (i32.store (i32.const 68) (call $frame-new (i32.const 1))))
  (func (export "stream.drop") (param $stream i32)
    (call $check-owner (local.get $stream))
    (call $drop (local.get $stream))
    (call $frame-drop (i32.load (i32.const 68)))
    (i32.store (i32.const 48) (i32.const 0))
    (i32.store (i32.const 56) (i32.const 0))
    (i32.store (i32.const 60) (i32.const 0))
    (i32.store (i32.const 68) (i32.const 0)))
  (func $read-buffer (param $stream i32) (param $data i32) (param $capacity i32) (result i32)
    (local $status i32) (local $length i32)
    (call $check-owner (local.get $stream))
    (if (i32.or (i32.load (i32.const 64)) (i32.eqz (local.get $capacity)))
      (then (return (i32.const 0))))
    (loop $read-again
      (local.set $status (call $read (local.get $stream) (local.get $data) (local.get $capacity)))
      ;; Synchronous canonical reads suspend; BLOCKED/CANCELLED cannot be returned.
      (if (i32.gt_u (i32.and (local.get $status) (i32.const 15)) (i32.const 1)) (then unreachable))
      (local.set $length (i32.shr_u (local.get $status) (i32.const 4)))
      (if (i32.gt_u (local.get $length) (local.get $capacity)) (then unreachable))
      (i32.store (i32.const 64) (i32.and (local.get $status) (i32.const 1)))
      (br_if $read-again (i32.and (i32.eqz (local.get $length)) (i32.eqz (i32.load (i32.const 64))))))
    (local.get $length))
  (func (export "stream.read-chunk") (param $stream i32) (result f64)
    (local $data i32) (local $length i32)
    (call $check-owner (local.get $stream))
    (local.set $data (i32.load (i32.const 56)))
    (if (i32.eqz (local.get $data))
      (then
        (local.set $data (call $realloc (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 8192)))
        (i32.store (i32.const 56) (local.get $data))
        (i32.store offset=12 (i32.load (i32.const 68)) (local.get $data))))
    (local.set $length (call $read-buffer (local.get $stream) (local.get $data) (i32.const 8192)))
    (i32.store (i32.const 60) (local.get $length))
    (f64.convert_i32_u (local.get $length)))
  (func (export "stream.read-into") (param $stream i32) (param $view i32) (result f64)
    (i32.store (i32.const 60) (i32.const 0))
    (f64.convert_i32_u (call $read-buffer (local.get $stream)
      (i32.load (local.get $view)) (i32.load offset=4 (local.get $view)))))
  (func (export "stream.byte-at") (param $index f64) (result f64)
    (local $integer i32)
    (if (i32.eqz (i32.load (i32.const 48))) (then unreachable))
    (if (f64.ne (local.get $index) (f64.trunc (local.get $index))) (then unreachable))
    (local.set $integer (i32.trunc_f64_u (local.get $index)))
    (if (i32.ge_u (local.get $integer) (i32.load (i32.const 60))) (then unreachable))
    (f64.convert_i32_u (i32.load8_u (i32.add (i32.load (i32.const 56)) (local.get $integer))))))
