(module
  (import "heap" "realloc" (func $realloc (param i32 i32 i32 i32) (result i32)))
  (memory 1)
  ;; Views: data address, visible byte count, backing allocation, backing offset.
  (func $view (param $owner i32) (param $offset i32) (param $length i32) (result i32)
    (local $view i32)
    (local.set $view (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 16)))
    (i32.store offset=16 (i32.load (i32.sub (local.get $view) (i32.const 4))) (i32.const 7))
    (i32.store (local.get $view) (i32.add (local.get $owner) (local.get $offset)))
    (i32.store offset=4 (local.get $view) (local.get $length))
    (i32.store offset=8 (local.get $view) (local.get $owner))
    (i32.store offset=12 (local.get $view) (local.get $offset))
    (local.get $view))
  (func $allocate (param $length i32) (result i32)
    (local $owner i32)
    (local.set $owner (call $realloc (i32.const 0) (i32.const 0) (i32.const 1)
      (if (result i32) (local.get $length) (then (local.get $length)) (else (i32.const 1)))))
    (memory.fill (local.get $owner) (i32.const 0) (local.get $length))
    (call $view (local.get $owner) (i32.const 0) (local.get $length)))
  (func (export "bytes.new") (param $size f64) (result i32 f64)
    (if (f64.ne (local.get $size) (local.get $size)) (then (local.set $size (f64.const 0))))
    (local.set $size (f64.trunc (local.get $size)))
    (if (i32.or (f64.lt (local.get $size) (f64.const 0)) (f64.gt (local.get $size) (f64.const 4294967295)))
      (then (return (i32.const 1) (f64.const 1))))
    (i32.const 0) (f64.convert_i32_u (call $allocate (i32.trunc_f64_u (local.get $size)))))
  (func (export "bytes.copy") (param $source i32) (result i32)
    (local $length i32) (local $result i32)
    (local.set $length (i32.load offset=4 (local.get $source)))
    (local.set $result (call $allocate (local.get $length)))
    (memory.copy (i32.load (local.get $result)) (i32.load (local.get $source)) (local.get $length))
    (local.get $result))
  (func $valid-index (param $view i32) (param $index f64) (result i32)
    (i32.and (f64.eq (local.get $index) (f64.trunc (local.get $index)))
      (i32.and (f64.ge (local.get $index) (f64.const 0))
        (f64.lt (local.get $index) (f64.convert_i32_u (i32.load offset=4 (local.get $view)))))))
  (func (export "bytes.get") (param $view i32) (param $index f64) (result f64)
    (if (i32.eqz (call $valid-index (local.get $view) (local.get $index))) (then (return (f64.const nan))))
    (f64.convert_i32_u (i32.load8_u (i32.add (i32.load (local.get $view)) (i32.trunc_f64_u (local.get $index))))))
  (func (export "bytes.set") (param $view i32) (param $index f64) (param $value f64)
    (if (i32.eqz (call $valid-index (local.get $view) (local.get $index))) (then return))
    (if (f64.lt (f64.abs (local.get $value)) (f64.const inf))
      (then
        (local.set $value (f64.trunc (local.get $value)))
        (local.set $value (f64.sub (local.get $value)
          (f64.mul (f64.floor (f64.div (local.get $value) (f64.const 256))) (f64.const 256)))))
      (else (local.set $value (f64.const 0))))
    (i32.store8 (i32.add (i32.load (local.get $view)) (i32.trunc_f64_u (local.get $index))) (i32.trunc_f64_u (local.get $value))))
  (func $bound (param $position f64) (param $length i32) (result i32)
    (if (f64.ne (local.get $position) (local.get $position)) (then (return (i32.const 0))))
    (local.set $position (f64.trunc (local.get $position)))
    (if (f64.lt (local.get $position) (f64.const 0))
      (then (local.set $position (f64.add (f64.convert_i32_u (local.get $length)) (local.get $position)))))
    (i32.trunc_f64_u (f64.min (f64.max (local.get $position) (f64.const 0)) (f64.convert_i32_u (local.get $length)))))
  (func (export "bytes.subarray") (param $source i32) (param $start f64) (param $end f64) (result i32)
    (local $begin i32) (local $finish i32) (local $length i32)
    (local.set $length (i32.load offset=4 (local.get $source)))
    (local.set $begin (call $bound (local.get $start) (local.get $length)))
    (local.set $finish (call $bound (local.get $end) (local.get $length)))
    (call $view (i32.load offset=8 (local.get $source))
      (i32.add (i32.load offset=12 (local.get $source)) (local.get $begin))
      (if (result i32) (i32.gt_u (local.get $finish) (local.get $begin))
        (then (i32.sub (local.get $finish) (local.get $begin))) (else (i32.const 0))))))
