(module
  (import "host" "realloc" (func $realloc (param i32 i32 i32 i32) (result i32)))
  (import "host" "box" (func $box (param i32 f64) (result i32)))
  (import "host" "compare" (func $compare (param i32 i32) (result i32)))
  (import "host" "string-index" (func $string-index (param i32 f64) (result i32)))
  (import "host" "object-get" (func $object-get (param i32 i32) (result i32)))
  (import "host" "object-set" (func $object-set (param i32 i32 i32 f64) (result i32 f64)))
  (import "host" "object-dynamic" (func $object-dynamic (param i32) (result i32)))
  (memory 1)

  (func $array-new (export "value.array-new") (param $count i32) (result i32) (local $array i32) (local $size i64)
    (local.set $size (i64.add (i64.const 8) (i64.mul (i64.extend_i32_u (local.get $count)) (i64.const 4))))
    (if (i64.gt_u (local.get $size) (i64.const 4294967295)) (then unreachable))
    (local.set $array (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.wrap_i64 (local.get $size))))
    (i32.store offset=16 (i32.load (i32.sub (local.get $array) (i32.const 4))) (i32.const 12))
    (i32.store (local.get $array) (i32.add (local.get $array) (i32.const 8)))
    (i32.store offset=4 (local.get $array) (local.get $count))
    (memory.fill (i32.load (local.get $array)) (i32.const 0) (i32.mul (local.get $count) (i32.const 4)))
    (local.get $array))

  (func $resize (export "value.array-resize") (param $array i32) (param $count i32)
    (local $data i32) (local $previous i32) (local $capacity i32) (local $inline i32) (local $next i32)
    (if (i32.gt_u (local.get $count) (i32.const 1073741821)) (then unreachable))
    (local.set $data (i32.load (local.get $array)))
    (local.set $previous (i32.load offset=4 (local.get $array)))
    (local.set $inline (i32.eq (local.get $data) (i32.add (local.get $array) (i32.const 8))))
    (if (local.get $inline)
      (then (local.set $capacity (i32.div_u (i32.sub (i32.load offset=12 (i32.load (i32.sub (local.get $array) (i32.const 4)))) (i32.const 8)) (i32.const 4))))
      (else (local.set $capacity (i32.div_u (i32.load offset=12 (i32.load (i32.sub (local.get $data) (i32.const 4)))) (i32.const 4)))))
    (if (i32.gt_u (local.get $count) (local.get $capacity)) (then
      (local.set $next (i32.mul (local.get $capacity) (i32.const 2)))
      (if (i32.lt_u (local.get $next) (i32.const 8)) (then (local.set $next (i32.const 8))))
      (if (i32.lt_u (local.get $next) (local.get $count)) (then (local.set $next (local.get $count))))
      (if (i32.gt_u (local.get $next) (i32.const 1073741821)) (then (local.set $next (local.get $count))))
      (local.set $next (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.mul (local.get $next) (i32.const 4))))
      (memory.copy (local.get $next) (local.get $data) (i32.mul (local.get $previous) (i32.const 4)))
      (if (i32.eqz (local.get $inline))
        (then (drop (call $realloc (local.get $data) (i32.mul (local.get $capacity) (i32.const 4)) (i32.const 4) (i32.const 0)))))
      (local.set $data (local.get $next))
      (i32.store (local.get $array) (local.get $data))))
    (if (i32.gt_u (local.get $count) (local.get $previous)) (then
      (memory.fill (i32.add (local.get $data) (i32.mul (local.get $previous) (i32.const 4))) (i32.const 0)
        (i32.mul (i32.sub (local.get $count) (local.get $previous)) (i32.const 4)))))
    (i32.store offset=4 (local.get $array) (local.get $count)))

  (func $position (param $key i32) (result f64)
    (local $tag i32) (local $text i32) (local $length i32) (local $index i32) (local $digit i32) (local $value f64)
    (local.set $tag (i32.load (local.get $key)))
    (if (i32.eq (local.get $tag) (i32.const 3)) (then (return (f64.load offset=8 (local.get $key)))))
    (if (i32.ne (local.get $tag) (i32.const 4)) (then (return (f64.const -1))))
    (local.set $text (i32.trunc_f64_u (f64.load offset=8 (local.get $key))))
    (local.set $length (i32.load offset=4 (local.get $text)))
    (local.set $text (i32.load (local.get $text)))
    (if (i32.or (i32.eqz (local.get $length)) (i32.gt_u (local.get $length) (i32.const 10)))
      (then (return (f64.const -1))))
    (if (i32.and (i32.gt_u (local.get $length) (i32.const 1)) (i32.eq (i32.load8_u (local.get $text)) (i32.const 48)))
      (then (return (f64.const -1))))
    (loop $digits
      (local.set $digit (i32.sub (i32.load8_u (i32.add (local.get $text) (local.get $index))) (i32.const 48)))
      (if (i32.gt_u (local.get $digit) (i32.const 9)) (then (return (f64.const -1))))
      (local.set $value (f64.add (f64.mul (local.get $value) (f64.const 10)) (f64.convert_i32_u (local.get $digit))))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br_if $digits (i32.lt_u (local.get $index) (local.get $length))))
    (local.get $value))
  (func $valid-position (param $index f64) (result i32)
    (i32.and (f64.ge (local.get $index) (f64.const 0))
      (i32.and (f64.lt (local.get $index) (f64.const 4294967295))
        (f64.eq (local.get $index) (f64.trunc (local.get $index))))))
  (func $is-length (param $key i32) (result i32)
    (if (i32.eq (i32.load (local.get $key)) (i32.const 4)) (then
      (return (i32.eqz (call $compare (i32.trunc_f64_u (f64.load offset=8 (local.get $key))) (i32.const {{length}}))))))
    (i32.const 0))

  (func (export "value.get") (param $value i32) (param $key i32) (result i32 f64)
    (local $tag i32) (local $pointer i32) (local $index f64) (local $result i32)
    (local.set $tag (i32.load (local.get $value)))
    (if (i32.le_u (local.get $tag) (i32.const 1)) (then (return (i32.const 1) (f64.const 12))))
    (if (i32.eq (local.get $tag) (i32.const 6)) (then
      (if (i32.ne (i32.load (local.get $key)) (i32.const 4)) (then (return (i32.const 1) (f64.const 12))))
      (return (i32.const 0) (f64.convert_i32_u (call $object-dynamic
        (call $object-get (i32.trunc_f64_u (f64.load offset=8 (local.get $value))) (i32.trunc_f64_u (f64.load offset=8 (local.get $key)))))))))
    (if (i32.or (i32.eq (local.get $tag) (i32.const {{array-tag}})) (i32.eq (local.get $tag) (i32.const 4))) (then
      (local.set $pointer (i32.trunc_f64_u (f64.load offset=8 (local.get $value))))
      (if (call $is-length (local.get $key)) (then
        (return (i32.const 0) (f64.convert_i32_u (call $box (i32.const 3)
          (f64.convert_i32_u (i32.load (i32.add (local.get $pointer)
            (select (i32.const 8) (i32.const 4) (i32.eq (local.get $tag) (i32.const 4)))))))))))
      (local.set $index (call $position (local.get $key)))
      (if (i32.eq (local.get $tag) (i32.const 4)) (then
        (local.set $result (call $string-index (local.get $pointer) (local.get $index)))
        (return (i32.const 0) (f64.convert_i32_u (call $box (select (i32.const 4) (i32.const 0) (local.get $result)) (f64.convert_i32_u (local.get $result)))))))
      (if (call $valid-position (local.get $index)) (then
        (if (f64.lt (local.get $index) (f64.convert_i32_u (i32.load offset=4 (local.get $pointer)))) (then
          (local.set $result (i32.load (i32.add (i32.load (local.get $pointer)) (i32.mul (i32.trunc_f64_u (local.get $index)) (i32.const 4)))))
          (if (local.get $result) (then (return (i32.const 0) (f64.convert_i32_u (local.get $result)))))))))))
    (i32.const 0) (f64.convert_i32_u (call $box (i32.const 0) (f64.const 0))))

  (func (export "value.set") (param $value i32) (param $key i32) (param $item i32) (result i32 f64)
    (local $tag i32) (local $pointer i32) (local $index f64) (local $position i32)
    (local.set $tag (i32.load (local.get $value)))
    (if (i32.eq (local.get $tag) (i32.const 6)) (then
      (if (i32.ne (i32.load (local.get $key)) (i32.const 4)) (then (return (i32.const 1) (f64.const 12))))
      (return (call $object-set (i32.trunc_f64_u (f64.load offset=8 (local.get $value)))
        (i32.trunc_f64_u (f64.load offset=8 (local.get $key))) (i32.load (local.get $item)) (f64.load offset=8 (local.get $item))))))
    (if (i32.ne (local.get $tag) (i32.const {{array-tag}})) (then (return (i32.const 1) (f64.const 12))))
    (local.set $pointer (i32.trunc_f64_u (f64.load offset=8 (local.get $value))))
    (if (call $is-length (local.get $key)) (then
      (if (i32.ne (i32.load (local.get $item)) (i32.const 3)) (then (return (i32.const 1) (f64.const 12))))
      (local.set $index (f64.load offset=8 (local.get $item)))
      (if (i32.eqz (i32.and (f64.ge (local.get $index) (f64.const 0))
        (i32.and (f64.le (local.get $index) (f64.const 4294967295)) (f64.eq (local.get $index) (f64.trunc (local.get $index))))))
        (then (return (i32.const 1) (f64.const 1))))
      (call $resize (local.get $pointer) (i32.trunc_f64_u (local.get $index)))
      (return (i32.const 0) (f64.const 0))))
    (local.set $index (call $position (local.get $key)))
    (if (i32.eqz (call $valid-position (local.get $index))) (then (return (i32.const 1) (f64.const 12))))
    (local.set $position (i32.trunc_f64_u (local.get $index)))
    (if (i32.ge_u (local.get $position) (i32.load offset=4 (local.get $pointer)))
      (then (call $resize (local.get $pointer) (i32.add (local.get $position) (i32.const 1)))))
    (i32.store (i32.add (i32.load (local.get $pointer)) (i32.mul (local.get $position) (i32.const 4))) (local.get $item))
    (i32.const 0) (f64.const 0))

  (func (export "value.has") (param $value i32) (param $key i32) (result i32 f64)
    (local $tag i32) (local $pointer i32) (local $index f64) (local $slot i32)
    (local.set $tag (i32.load (local.get $value)))
    (if (i32.eq (local.get $tag) (i32.const 6)) (then
      (if (i32.ne (i32.load (local.get $key)) (i32.const 4)) (then (return (i32.const 1) (f64.const 12))))
      (local.set $pointer (i32.trunc_f64_u (f64.load offset=8 (local.get $value))))
      (local.set $slot (i32.trunc_f64_u (f64.load offset=8 (local.get $key))))
      (return (i32.const 0) (f64.convert_i32_u (i32.ne (call $object-get (local.get $pointer) (local.get $slot)) (i32.const 0))))))
    (if (i32.ne (local.get $tag) (i32.const {{array-tag}})) (then (return (i32.const 1) (f64.const 12))))
    (if (call $is-length (local.get $key)) (then
      (return (i32.const 0) (f64.const 1))))
    (local.set $index (call $position (local.get $key)))
    (local.set $pointer (i32.trunc_f64_u (f64.load offset=8 (local.get $value))))
    (if (call $valid-position (local.get $index)) (then
      (if (f64.lt (local.get $index) (f64.convert_i32_u (i32.load offset=4 (local.get $pointer)))) (then
        (local.set $slot (i32.add (i32.load (local.get $pointer)) (i32.mul (i32.trunc_f64_u (local.get $index)) (i32.const 4))))
        (return (i32.const 0) (f64.convert_i32_u (i32.ne (i32.load (local.get $slot)) (i32.const 0))))))))
    (i32.const 0) (f64.const 0))
)
