  (func (export "process.argv") (result i32)
    (local $cache i32) (local $value i32) (local $result i32) (local $data i32) (local $count i32)
    (local.set $cache (call $cache))
    (local.set $value (i32.load offset=12 (local.get $cache)))
    (if (local.get $value) (then (return (local.get $value))))
    (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 8)))
    (call $get-arguments (local.get $result))
    (local.set $data (i32.load (local.get $result)))
    (local.set $count (i32.load offset=4 (local.get $result)))
    (local.set $value (call $strings (local.get $data) (local.get $count)))
    (drop (call $realloc (local.get $result) (i32.const 8) (i32.const 4) (i32.const 0)))
    (i32.store offset=12 (local.get $cache) (local.get $value))
    (local.get $value))
