  (func (export "process.cwd") (result i32)
    (local $cache i32) (local $value i32) (local $result i32) (local $data i32) (local $length i32)
    (local.set $cache (call $cache))
    (local.set $value (i32.load offset=16 (local.get $cache)))
    (if (local.get $value) (then (return (local.get $value))))
    (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 12)))
    (call $get-initial-cwd (local.get $result))
    (if (i32.load8_u (local.get $result))
      (then
        (local.set $data (i32.load offset=4 (local.get $result)))
        (local.set $length (i32.load offset=8 (local.get $result))))
      (else
        (local.set $data (call $realloc (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 1)))
        (i32.store8 (local.get $data) (i32.const 47))
        (local.set $length (i32.const 1))))
    (local.set $value (call $string (local.get $data) (local.get $length)))
    (drop (call $realloc (local.get $result) (i32.const 12) (i32.const 4) (i32.const 0)))
    (i32.store offset=16 (local.get $cache) (local.get $value))
    (local.get $value))
