  (func (export "process.env") (result i32)
    (local $cache i32) (local $value i32) (local $result i32) (local $data i32) (local $count i32)
    (local $index i32) (local $entry i32) (local $key i32) (local $text i32)
    (local.set $cache (call $cache))
    (local.set $value (i32.load offset=20 (local.get $cache)))
    (if (local.get $value) (then (return (local.get $value))))
    (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 8)))
    (call $get-environment (local.get $result))
    (local.set $data (i32.load (local.get $result)))
    (local.set $count (i32.load offset=4 (local.get $result)))
    (if (i32.gt_u (local.get $count) (i32.const 268435455)) (then unreachable))
    (local.set $value (call $environment))
    (block $done (loop $entries
      (br_if $done (i32.eq (local.get $index) (local.get $count)))
      (local.set $entry (i32.add (local.get $data) (i32.mul (local.get $index) (i32.const 16))))
      (local.set $key (call $string (i32.load (local.get $entry)) (i32.load offset=4 (local.get $entry))))
      (local.set $text (call $string (i32.load offset=8 (local.get $entry)) (i32.load offset=12 (local.get $entry))))
      (call $set (local.get $value) (local.get $key) (i32.const 4) (f64.convert_i32_u (local.get $text)))
      drop drop
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $entries)))
    (drop (call $realloc (local.get $data) (i32.mul (local.get $count) (i32.const 16)) (i32.const 4) (i32.const 0)))
    (drop (call $realloc (local.get $result) (i32.const 8) (i32.const 4) (i32.const 0)))
    (i32.store offset=8 (local.get $value) (i32.const 1))
    (i32.store offset=20 (local.get $cache) (local.get $value))
    (local.get $value))
