  (import "host" "finish-write" (func $finish-write (param i32 i32 i32)))
  (import "host" "read-buffered" (func $read-buffered (param i32 i32) (result i32 i32 i32)))
  (import "host" "realloc" (func $realloc (param i32 i32 i32 i32) (result i32)))
  (import "host" "frame-new" (func $frame-new (param i32) (result i32)))
  (import "host" "frame-drop" (func $frame-drop (param i32)))
  (import "host" "cleanup" (func $cleanup))
  (import "host" "handle" (func $handle (param i32) (result i32)))

  (func (export "handle") (param $request i32)
    (local $frame i32) (local $input i32) (local $scratch i32) (local $fields i32)
    (local $ack i64) (local $ack-writer i32) (local $reader i32) (local $trailers-reader i32)
    (local $data i32) (local $length i32) (local $error i32) (local $reply i32)
    (local $stream i64) (local $writer i32) (local $trailers i64) (local $trailers-writer i32)
    (local $response i32) (local $completion i32) (local $written i32)
    (call $backpressure-inc)
    (local.set $frame (call $frame-new (i32.const 3)))
    (local.set $scratch (call $realloc (i32.const 0) (i32.const 0) (i32.const 8) (i32.const 256)))
    (i32.store offset=12 (local.get $frame) (local.get $scratch))
    (memory.fill (local.get $scratch) (i32.const 0) (i32.const 256))
    (local.set $input (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 68)))
    (i32.store offset=16 (local.get $frame) (local.get $input))
    (memory.fill (local.get $input) (i32.const 0) (i32.const 68))
    (call $method (local.get $request) (local.get $input))
    (call $scheme (local.get $request) (i32.add (local.get $input) (i32.const 12)))
    (call $authority (local.get $request) (i32.add (local.get $input) (i32.const 28)))
    (call $path (local.get $request) (i32.add (local.get $input) (i32.const 40)))
    (local.set $fields (call $headers (local.get $request)))
    (call $copy-fields (local.get $fields) (i32.add (local.get $input) (i32.const 52)))
    (call $drop-fields (local.get $fields))
    (local.set $ack (call $new-completion))
    (local.set $ack-writer (i32.wrap_i64 (i64.shr_u (local.get $ack) (i64.const 32))))
    (call $consume (local.get $request) (i32.wrap_i64 (local.get $ack)) (local.get $scratch))
    (local.set $reader (i32.load (local.get $scratch)))
    (local.set $trailers-reader (i32.load offset=4 (local.get $scratch)))
    (call $read-buffered (local.get $reader) (i32.const REQUEST_LIMIT))
    local.set $length local.set $data local.set $error
    (local.set $error (i32.mul (local.get $error) (i32.const 17)))
    (i32.store offset=60 (local.get $input) (local.get $data))
    (i32.store offset=64 (local.get $input) (local.get $length))
    (i32.store offset=20 (local.get $frame) (local.get $data))
    (call $drop-reader (local.get $reader))
    (if (call $read-trailers (local.get $trailers-reader) (local.get $scratch)) (then unreachable))
    (call $drop-trailers-reader (local.get $trailers-reader))
    (if (i32.load8_u (local.get $scratch))
      (then (if (i32.eqz (local.get $error)) (then (local.set $error (i32.const 38)))))
      (else (if (i32.load8_u offset=8 (local.get $scratch)) (then (call $drop-fields (i32.load offset=12 (local.get $scratch)))))))
    (if (local.get $error) (then
      (i32.store offset=64 (local.get $scratch) (i32.const 1))
      (i32.store offset=72 (local.get $scratch) (local.get $error))))
    (call $finish-write (local.get $ack-writer)
      (call $write-completion (local.get $ack-writer) (i32.add (local.get $scratch) (i32.const 64)))
      (i32.add (local.get $scratch) (i32.const 192)))
    (call $drop-completion-writer (local.get $ack-writer))

    (block $failed
      (br_if $failed (local.get $error))
      (local.set $reply (call $handle (local.get $input)))
      (local.set $data (i32.load offset=12 (local.get $reply)))
      (local.set $length (i32.load offset=16 (local.get $reply)))
      (if (i32.gt_u (local.get $length) (i32.const RESPONSE_LIMIT)) (then
        (local.set $error (i32.const 28)) (br $failed)))
      (local.set $response (i32.load16_u (local.get $reply)))
      (if (i32.or (i32.lt_u (local.get $response) (i32.const 200))
        (i32.gt_u (local.get $response) (i32.const 599))) (then
        (local.set $error (i32.const 38)) (br $failed)))
      (if (i32.and (i32.ne (local.get $length) (i32.const 0))
        (i32.or (i32.eq (local.get $response) (i32.const 204))
          (i32.or (i32.eq (local.get $response) (i32.const 205)) (i32.eq (local.get $response) (i32.const 304)))))
        (then (local.set $error (i32.const 38)) (br $failed)))
      (call $fields (i32.load offset=4 (local.get $reply)) (i32.load offset=8 (local.get $reply)) (local.get $scratch))
      (if (i32.load8_u (local.get $scratch)) (then (local.set $error (i32.const 38)) (br $failed)))
      (local.set $stream (call $new-stream))
      (local.set $writer (i32.wrap_i64 (i64.shr_u (local.get $stream) (i64.const 32))))
      (local.set $trailers (call $new-trailers))
      (local.set $trailers-writer (i32.wrap_i64 (i64.shr_u (local.get $trailers) (i64.const 32))))
      (call $response (i32.load offset=4 (local.get $scratch)) (i32.const 1)
        (i32.wrap_i64 (local.get $stream)) (i32.wrap_i64 (local.get $trailers)) (local.get $scratch))
      (local.set $response (i32.load (local.get $scratch)))
      (local.set $completion (i32.load offset=4 (local.get $scratch)))
      (if (call $status (local.get $response) (i32.load16_u (local.get $reply))) (then unreachable))
      (call $return (i32.const 0) (local.get $response) (i32.const 0) (i64.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0))
      (local.set $written (call $write-buffer (local.get $writer) (local.get $data) (local.get $length)))
      (call $drop-writer (local.get $writer))
      (if (i32.ne (local.get $written) (local.get $length)) (then
        (i32.store offset=128 (local.get $scratch) (i32.const 1))
        (i32.store offset=136 (local.get $scratch) (i32.const 25))))
      (call $finish-write (local.get $trailers-writer)
        (call $write-trailers (local.get $trailers-writer) (i32.add (local.get $scratch) (i32.const 128)))
        (i32.add (local.get $scratch) (i32.const 192)))
      (call $drop-trailers-writer (local.get $trailers-writer))
      (if (call $read-completion (local.get $completion) (local.get $scratch)) (then unreachable))
      (call $drop-completion-reader (local.get $completion)))
    (if (local.get $error) (then
      (call $return (i32.const 1) (local.get $error) (i32.const 0) (i64.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0))))
    (call $frame-drop (local.get $frame))
    (call $cleanup)
    (call $backpressure-dec))
