//! WIT to TypeScript declaration (.d.ts) code generator.
//!
//! Generates idiomatic, strongly-typed TypeScript definitions for WIT worlds,
//! exported functions, records, variants, enums, and imported interfaces.

use anyhow::Result;
use std::collections::HashSet;
use std::path::Path;
use wit_parser::{
    Function, Resolve, Result_ as WitResult, Type, TypeDefKind, World, WorldItem, WorldKey,
};

/// Converts a kebab-case or snake_case string into camelCase.
pub fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = false;
    for (i, c) in s.chars().enumerate() {
        if c == '-' || c == '_' || c == ':' || c == '/' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else if i == 0 {
            result.push(c.to_ascii_lowercase());
        } else {
            result.push(c);
        }
    }
    result
}

/// Converts a kebab-case or snake_case string into PascalCase.
pub fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    for c in s.chars() {
        if c == '-' || c == '_' || c == ':' || c == '/' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }
    result
}

/// Formats a WIT Type into its corresponding TypeScript representation.
pub fn wit_type_to_ts(resolve: &Resolve, ty: &Type) -> String {
    match ty {
        Type::Bool => "boolean".to_string(),
        Type::U8
        | Type::U16
        | Type::U32
        | Type::S8
        | Type::S16
        | Type::S32
        | Type::F32
        | Type::F64 => "number".to_string(),
        Type::U64 | Type::S64 => "bigint".to_string(),
        Type::Char | Type::String => "string".to_string(),
        Type::ErrorContext => "Error | unknown".to_string(),
        Type::Id(id) => {
            let type_def = &resolve.types[*id];
            if let Some(name) = &type_def.name {
                to_pascal_case(name)
            } else {
                type_kind_to_ts(resolve, &type_def.kind)
            }
        }
    }
}

fn type_kind_to_ts(resolve: &Resolve, kind: &TypeDefKind) -> String {
    match kind {
        TypeDefKind::List(elem) => {
            if matches!(elem, Type::U8) {
                "Uint8Array".to_string()
            } else {
                format!("Array<{}>", wit_type_to_ts(resolve, elem))
            }
        }
        TypeDefKind::Option(inner) => {
            format!("{} | null | undefined", wit_type_to_ts(resolve, inner))
        }
        TypeDefKind::Result(WitResult { ok, err }) => {
            let ok_str = ok
                .as_ref()
                .map(|t| wit_type_to_ts(resolve, t))
                .unwrap_or_else(|| "void".to_string());
            let err_str = err
                .as_ref()
                .map(|t| wit_type_to_ts(resolve, t))
                .unwrap_or_else(|| "unknown".to_string());
            format!("{{ ok: true; value: {ok_str} }} | {{ ok: false; error: {err_str} }}")
        }
        TypeDefKind::Tuple(tuple) => {
            let items: Vec<String> = tuple
                .types
                .iter()
                .map(|t| wit_type_to_ts(resolve, t))
                .collect();
            format!("[{}]", items.join(", "))
        }
        _ => "unknown".to_string(),
    }
}

/// Formats a WIT function return type into TypeScript.
pub fn wit_result_to_ts(resolve: &Resolve, func: &Function) -> String {
    match &func.result {
        None => "void".to_string(),
        Some(ty) => wit_type_to_ts(resolve, ty),
    }
}

/// Generates TypeScript declarations (.d.ts) for a given WIT world.
pub fn generate_world_declarations(resolve: &Resolve, world: &World) -> Result<String> {
    let mut out = String::new();

    out.push_str("/**\n");
    out.push_str(&format!(
        " * Auto-generated TypeScript definitions for WIT world `{}`.\n",
        world.name
    ));
    out.push_str(" * Generated by Perry-WIT SDK compiler.\n");
    out.push_str(" */\n\n");

    let mut emitted_types = HashSet::new();

    // 1. Collect and emit named types referenced in world or interfaces (imports & exports)
    for (_, item) in world.imports.iter().chain(world.exports.iter()) {
        match item {
            WorldItem::Interface { id, .. } => {
                let iface = &resolve.interfaces[*id];
                for (name, &type_id) in &iface.types {
                    emit_type_def(resolve, type_id, name, &mut emitted_types, &mut out);
                }
            }
            WorldItem::Function(func) => {
                for param in &func.params {
                    emit_nested_types(resolve, &param.ty, &mut emitted_types, &mut out);
                }
                if let Some(ret) = &func.result {
                    emit_nested_types(resolve, ret, &mut emitted_types, &mut out);
                }
            }
            WorldItem::Type { id: type_id, .. } => {
                let td = &resolve.types[*type_id];
                if let Some(name) = &td.name {
                    emit_type_def(resolve, *type_id, name, &mut emitted_types, &mut out);
                }
            }
        }
    }

    // 2. Emit exported functions
    out.push_str("/* =========================================================================\n");
    out.push_str(
        " * Exported Component Functions (Implement and export in your TypeScript file)\n",
    );
    out.push_str(
        " * ========================================================================= */\n\n",
    );

    for (key, item) in &world.exports {
        match item {
            WorldItem::Function(func) => {
                let export_name = match key {
                    WorldKey::Name(name) => name.clone(),
                    WorldKey::Interface(_) => func.name.clone(),
                };
                let ts_func_name = to_camel_case(&export_name);
                let ret_ty = wit_result_to_ts(resolve, func);

                let params_str: Vec<String> = func
                    .params
                    .iter()
                    .map(|param| {
                        format!(
                            "{}: {}",
                            to_camel_case(&param.name),
                            wit_type_to_ts(resolve, &param.ty)
                        )
                    })
                    .collect();

                let params_decl = params_str.join(", ");

                out.push_str(&format!("/**\n * WIT export: `{export_name}`\n */\n"));
                out.push_str(&format!(
                    "export declare function {ts_func_name}({params_decl}): {ret_ty};\n"
                ));

                // Also generate a type signature alias
                let type_alias_name = format!("{}Fn", to_pascal_case(&export_name));
                out.push_str(&format!(
                    "export type {type_alias_name} = ({params_decl}) => {ret_ty};\n\n"
                ));
            }
            WorldItem::Interface { id, .. } => {
                let iface = &resolve.interfaces[*id];
                let iface_name = match key {
                    WorldKey::Name(n) => to_pascal_case(n),
                    WorldKey::Interface(_) => iface
                        .name
                        .as_deref()
                        .map(to_pascal_case)
                        .unwrap_or_else(|| "ExportedInterface".to_string()),
                };

                out.push_str(&format!("export namespace {iface_name} {{\n"));
                for (_, func) in &iface.functions {
                    let ts_name = to_camel_case(&func.name);
                    let ret_ty = wit_result_to_ts(resolve, func);
                    let params_str: Vec<String> = func
                        .params
                        .iter()
                        .map(|param| {
                            format!(
                                "{}: {}",
                                to_camel_case(&param.name),
                                wit_type_to_ts(resolve, &param.ty)
                            )
                        })
                        .collect();
                    out.push_str(&format!(
                        "  export function {ts_name}({}): {ret_ty};\n",
                        params_str.join(", ")
                    ));
                }
                out.push_str("}\n\n");
            }
            _ => {}
        }
    }

    Ok(out)
}

fn emit_nested_types(
    resolve: &Resolve,
    ty: &Type,
    emitted: &mut HashSet<String>,
    out: &mut String,
) {
    if let Type::Id(id) = ty {
        let td = &resolve.types[*id];
        if let Some(name) = &td.name {
            emit_type_def(resolve, *id, name, emitted, out);
        } else {
            for child in type_children(&td.kind) {
                emit_nested_types(resolve, child, emitted, out);
            }
        }
    }
}

fn type_children(kind: &TypeDefKind) -> Vec<&Type> {
    match kind {
        TypeDefKind::List(inner) | TypeDefKind::Option(inner) | TypeDefKind::Type(inner) => {
            vec![inner]
        }
        TypeDefKind::Result(result) => result.ok.iter().chain(result.err.iter()).collect(),
        TypeDefKind::Tuple(tuple) => tuple.types.iter().collect(),
        TypeDefKind::Record(record) => record.fields.iter().map(|field| &field.ty).collect(),
        TypeDefKind::Variant(variant) => variant
            .cases
            .iter()
            .filter_map(|case| case.ty.as_ref())
            .collect(),
        _ => Vec::new(),
    }
}

fn emit_type_def(
    resolve: &Resolve,
    type_id: wit_parser::TypeId,
    name: &str,
    emitted: &mut HashSet<String>,
    out: &mut String,
) {
    let type_name = to_pascal_case(name);
    if emitted.contains(&type_name) {
        return;
    }

    let mut current_id = type_id;
    let mut current_td = &resolve.types[current_id];
    while let TypeDefKind::Type(Type::Id(inner_id)) = &current_td.kind {
        current_id = *inner_id;
        current_td = &resolve.types[current_id];
    }

    emitted.insert(type_name.clone());

    let td = current_td;
    match &td.kind {
        TypeDefKind::Record(record) => {
            out.push_str(&format!("export interface {type_name} {{\n"));
            for field in &record.fields {
                let fname = to_camel_case(&field.name);
                let fty = wit_type_to_ts(resolve, &field.ty);
                out.push_str(&format!("  {fname}: {fty};\n"));
            }
            out.push_str("}\n\n");
        }
        TypeDefKind::Enum(en) => {
            let cases: Vec<String> = en.cases.iter().map(|c| format!("\"{}\"", c.name)).collect();
            out.push_str(&format!(
                "export type {type_name} = {};\n\n",
                cases.join(" | ")
            ));
        }
        TypeDefKind::Variant(var) => {
            let cases: Vec<String> = var
                .cases
                .iter()
                .map(|c| {
                    if let Some(payload) = &c.ty {
                        let ty_str = wit_type_to_ts(resolve, payload);
                        format!("{{ tag: \"{}\"; val: {ty_str} }}", c.name)
                    } else {
                        format!("{{ tag: \"{}\" }}", c.name)
                    }
                })
                .collect();
            out.push_str(&format!(
                "export type {type_name} =\n  | {};\n\n",
                cases.join("\n  | ")
            ));
        }
        TypeDefKind::Flags(flags) => {
            out.push_str(&format!("export interface {type_name} {{\n"));
            for f in &flags.flags {
                out.push_str(&format!("  {}?: boolean;\n", to_camel_case(&f.name)));
            }
            out.push_str("}\n\n");
        }
        TypeDefKind::Type(alias) => {
            let alias_ty = wit_type_to_ts(resolve, alias);
            out.push_str(&format!("export type {type_name} = {alias_ty};\n\n"));
        }
        TypeDefKind::List(_)
        | TypeDefKind::Option(_)
        | TypeDefKind::Tuple(_)
        | TypeDefKind::Result(_) => {
            out.push_str(&format!(
                "export type {type_name} = {};\n\n",
                type_kind_to_ts(resolve, &td.kind)
            ));
        }
        _ => {}
    }
    for child in type_children(&td.kind) {
        emit_nested_types(resolve, child, emitted, out);
    }
}

/// Generates declarations for a WIT directory and target world name.
pub fn generate_declarations_from_wit_dir(
    wit_dir: &Path,
    world_name: Option<&str>,
) -> Result<(String, String)> {
    let (resolve, pkg_id) = crate::component::wit::resolve_wit(wit_dir)?;
    let pkg = &resolve.packages[pkg_id];

    let target_world_id = if let Some(wname) = world_name {
        pkg.worlds
            .get(wname)
            .copied()
            .ok_or_else(|| anyhow::anyhow!("World `{wname}` not found in WIT package"))?
    } else if let Some((_, &first_world)) = pkg.worlds.iter().next() {
        first_world
    } else {
        anyhow::bail!("No worlds found in WIT package at {}", wit_dir.display());
    };

    let world = &resolve.worlds[target_world_id];
    let dts = generate_world_declarations(&resolve, world)?;
    Ok((world.name.clone(), dts))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_camel_case() {
        assert_eq!(to_camel_case("run-task"), "runTask");
        assert_eq!(to_camel_case("merge_docs"), "mergeDocs");
        assert_eq!(to_camel_case("simple"), "simple");
        assert_eq!(to_camel_case("alreadyCamelCase"), "alreadyCamelCase");
    }

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("merge-task"), "MergeTask");
        assert_eq!(to_pascal_case("job_runner"), "JobRunner");
        assert_eq!(to_pascal_case("world"), "World");
    }

    #[test]
    fn test_generate_declarations_for_merge_task_world() {
        let (world_name, dts) =
            generate_declarations_from_wit_dir(Path::new("wit"), Some("merge-task"))
                .expect("Failed to generate declarations");

        assert_eq!(world_name, "merge-task");
        assert!(dts.contains("export declare function runTask(input: string): string;"));
        assert!(dts.contains("export declare function mergeTask(input: string): string;"));
        assert!(dts.contains("export type RunTaskFn = (input: string) => string;"));
    }

    #[test]
    fn test_generate_declarations_with_complex_types() {
        let tmp = std::env::temp_dir().join("perry_wit_test_types_wit");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        let wit_code = r#"
package test:complex;

interface types {
    record payload {
        id: u32,
        title: string,
        tags: list<string>,
        meta: option<string>,
    }

    enum status {
        pending,
        active,
        failed,
    }

    variant output-result {
        success(string),
        failure(u32),
    }
}

world complex-processor {
    use types.{payload, status, output-result};
    export process: func(data: payload, stat: status) -> output-result;
}
"#;
        std::fs::write(tmp.join("world.wit"), wit_code).unwrap();

        let (world_name, dts) = generate_declarations_from_wit_dir(&tmp, Some("complex-processor"))
            .expect("Failed to generate declarations for complex types");

        assert_eq!(world_name, "complex-processor");
        assert!(dts.contains("export interface Payload {"));
        assert!(dts.contains("id: number;"));
        assert!(dts.contains("title: string;"));
        assert!(dts.contains("tags: Array<string>;"));
        assert!(dts.contains("meta: string | null | undefined;"));
        assert!(dts.contains("export type Status = \"pending\" | \"active\" | \"failed\";"));
        assert!(dts.contains("export type OutputResult ="));
        assert!(dts.contains("tag: \"success\"; val: string"));
        assert!(dts.contains("tag: \"failure\"; val: number"));
        assert!(dts.contains(
            "export declare function process(data: Payload, stat: Status): OutputResult;"
        ));

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
