package perry:demo@0.1.0;

world command {
  include wasi:cli/command@0.3.0;
  import wasi:http/client@0.3.0;
}

world merge-docs {
  import wasi:http/client@0.3.0;
  export merge-docs: async func() -> string;
}

world task-runner {
  include wasi:cli/imports@0.3.0;
  export run-task: func(input: string) -> string;
}

world merge-task {
  include wasi:cli/imports@0.3.0;
  export run-task: func(input: string) -> string;
  export merge-task: func(input: string) -> string;
}
