package example:task@0.1.0;

world task {
    include wasi:cli/command@0.2.6;
    import wasi:http/outgoing-handler@0.2.6;
    import wasi:http/types@0.2.6;

    export run-task: func(input: string) -> string;
}
