  ;; Typed dictionaries enumerate in insertion order, including numeric-looking keys.
  (func (export "object.enumerate") (param $object i32) (param $values i32) (result i32 f64)
    (local $count i32) (local $entry i32) (local $index i32)
    (local $result i32) (local $descriptor i32)
    (local.set $entry (i32.load (local.get $object)))
    (block $counted (loop $count
      (br_if $counted (i32.eqz (local.get $entry)))
      (if (i32.and (local.get $values) (i32.ne (i32.load offset=8 (local.get $entry)) (i32.const 4)))
        (then (return (i32.const 1) (f64.const 12))))
      (local.set $count (i32.add (local.get $count) (i32.const 1)))
      (if (i32.gt_u (local.get $count) (i32.const 357913940)) (then unreachable))
      (local.set $entry (i32.load (local.get $entry)))
      (br $count)))
    (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.add (i32.const 8) (i32.mul (local.get $count) (i32.const 12)))))
    (i32.store offset=16 (i32.load (i32.sub (local.get $result) (i32.const 4))) (i32.const 2))
    (i32.store (local.get $result) (i32.add (local.get $result) (i32.const 8)))
    (i32.store offset=4 (local.get $result) (local.get $count))
    (local.set $entry (i32.load (local.get $object)))
    (block $copied (loop $copy
      (br_if $copied (i32.eqz (local.get $entry)))
      (if (local.get $values)
        (then (local.set $descriptor (i32.trunc_f64_u (f64.load offset=16 (local.get $entry)))))
        (else (local.set $descriptor (i32.load offset=4 (local.get $entry)))))
      (memory.copy (i32.add (i32.add (local.get $result) (i32.const 8)) (i32.mul (local.get $index) (i32.const 12))) (local.get $descriptor) (i32.const 12))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (local.set $entry (i32.load (local.get $entry)))
      (br $copy)))
    (i32.const 0) (f64.convert_i32_u (local.get $result)))

  (func $assign (export "object.assign") (param $target i32) (param $source i32) (result i32 f64)
    (local $entry i32)
    (local $status i32) (local $payload f64)
    (local.set $entry (i32.load (local.get $source)))
    (block $done (loop $copy
      (br_if $done (i32.eqz (local.get $entry)))
      (call $set (local.get $target) (i32.load offset=4 (local.get $entry))
        (i32.load offset=8 (local.get $entry)) (f64.load offset=16 (local.get $entry)))
      local.set $payload local.set $status
      (br_if $done (local.get $status))
      (local.set $entry (i32.load (local.get $entry)))
      (br $copy)))
    (local.get $status) (local.get $payload))

  ;; Non-string primitives have no enumerable fields. Other reference kinds are unsupported.
  (func (export "object.spread") (param $target i32) (param $tag i32) (param $payload f64) (result i32 f64)
    (if (i32.lt_u (local.get $tag) (i32.const 4))
      (then (return (i32.const 0) (f64.const 0))))
    (if (i32.ne (local.get $tag) (i32.const 6))
      (then (return (i32.const 1) (f64.const 12))))
    (call $assign (local.get $target) (i32.trunc_f64_u (local.get $payload))))
