  ;; Canonical array-index keys sort before other keys, which retain insertion order.
  (func $key-index (param $key i32) (result i32)
    (local $data i32) (local $length i32) (local $index i32) (local $digit i32) (local $value i64)
    (local.set $data (i32.load (local.get $key)))
    (local.set $length (i32.load offset=4 (local.get $key)))
    (if (i32.or (i32.eqz (local.get $length)) (i32.gt_u (local.get $length) (i32.const 10))) (then (return (i32.const -1))))
    (if (i32.and (i32.gt_u (local.get $length) (i32.const 1)) (i32.eq (i32.load8_u (local.get $data)) (i32.const 48)))
      (then (return (i32.const -1))))
    (loop $digits
      (local.set $digit (i32.sub (i32.load8_u (i32.add (local.get $data) (local.get $index))) (i32.const 48)))
      (if (i32.gt_u (local.get $digit) (i32.const 9)) (then (return (i32.const -1))))
      (local.set $value (i64.add (i64.mul (local.get $value) (i64.const 10)) (i64.extend_i32_u (local.get $digit))))
      (if (i64.ge_u (local.get $value) (i64.const 4294967295)) (then (return (i32.const -1))))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br_if $digits (i32.lt_u (local.get $index) (local.get $length))))
    (i32.wrap_i64 (local.get $value)))

  (func $enumerate (export "object.enumerate") (param $object i32) (param $values i32) (result i32 f64)
    (local $count i32) (local $entry i32) (local $order i32) (local $index i32)
    (local $ordinal i32) (local $position i32) (local $slot i32) (local $previous i32)
    (local $result i32) (local $descriptor i32)
    (local.set $entry (i32.load (local.get $object)))
    (block $counted (loop $count
      (br_if $counted (i32.eqz (local.get $entry)))
      (if (i32.and (local.get $values) (i32.ne (i32.load offset=8 (local.get $entry)) (i32.const 4)))
        (then (return (i32.const 1) (f64.const 12))))
      (local.set $count (i32.add (local.get $count) (i32.const 1)))
      (if (i32.gt_u (local.get $count) (i32.const 357913940)) (then unreachable))
      (local.set $entry (i32.load (local.get $entry)))
      (br $count)))
    (local.set $order (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.mul (local.get $count) (i32.const 8))))
    (local.set $entry (i32.load (local.get $object)))
    (block $ordered (loop $sort
      (br_if $ordered (i32.eqz (local.get $entry)))
      (local.set $ordinal (call $key-index (i32.load offset=4 (local.get $entry))))
      (local.set $position (local.get $index))
      (block $insert (loop $shift
        (br_if $insert (i32.eqz (local.get $position)))
        (local.set $previous (i32.add (local.get $order) (i32.mul (i32.sub (local.get $position) (i32.const 1)) (i32.const 8))))
        (br_if $insert (i32.ge_u (local.get $ordinal) (i32.load offset=4 (local.get $previous))))
        (memory.copy (i32.add (local.get $previous) (i32.const 8)) (local.get $previous) (i32.const 8))
        (local.set $position (i32.sub (local.get $position) (i32.const 1)))
        (br $shift)))
      (local.set $slot (i32.add (local.get $order) (i32.mul (local.get $position) (i32.const 8))))
      (i32.store (local.get $slot) (local.get $entry))
      (i32.store offset=4 (local.get $slot) (local.get $ordinal))
      (local.set $entry (i32.load (local.get $entry)))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $sort)))
    (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.add (i32.const 8) (i32.mul (local.get $count) (i32.const 12)))))
    (i32.store offset=16 (i32.load (i32.sub (local.get $result) (i32.const 4))) (i32.const 2))
    (i32.store (local.get $result) (i32.add (local.get $result) (i32.const 8)))
    (i32.store offset=4 (local.get $result) (local.get $count))
    (local.set $index (i32.const 0))
    (block $copied (loop $copy
      (br_if $copied (i32.eq (local.get $index) (local.get $count)))
      (local.set $entry (i32.load (i32.add (local.get $order) (i32.mul (local.get $index) (i32.const 8)))))
      (if (local.get $values)
        (then (local.set $descriptor (i32.trunc_f64_u (f64.load offset=16 (local.get $entry)))))
        (else (local.set $descriptor (i32.load offset=4 (local.get $entry)))))
      (memory.copy (i32.add (i32.add (local.get $result) (i32.const 8)) (i32.mul (local.get $index) (i32.const 12))) (local.get $descriptor) (i32.const 12))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $copy)))
    (drop (call $realloc (local.get $order) (i32.mul (local.get $count) (i32.const 8)) (i32.const 4) (i32.const 0)))
    (i32.const 0) (f64.convert_i32_u (local.get $result)))

  (func (export "object.assign") (param $target i32) (param $source i32) (result i32 f64)
    (local $keys i32) (local $count i32) (local $index i32) (local $entry i32)
    (local $status i32) (local $payload f64)
    (call $enumerate (local.get $source) (i32.const 0))
    local.set $payload local.set $status
    (if (local.get $status) (then (return (local.get $status) (local.get $payload))))
    (local.set $keys (i32.trunc_f64_u (local.get $payload)))
    (local.set $count (i32.load offset=4 (local.get $keys)))
    (block $done (loop $copy
      (br_if $done (i32.eq (local.get $index) (local.get $count)))
      (local.set $entry (call $get (local.get $source)
        (i32.add (i32.load (local.get $keys)) (i32.mul (local.get $index) (i32.const 12)))))
      (call $set (local.get $target) (i32.load offset=4 (local.get $entry))
        (i32.load offset=8 (local.get $entry)) (f64.load offset=16 (local.get $entry)))
      local.set $payload local.set $status
      (br_if $done (local.get $status))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $copy)))
    (drop (call $realloc (local.get $keys) (i32.add (i32.const 8) (i32.mul (local.get $count) (i32.const 12))) (i32.const 4) (i32.const 0)))
    (local.get $status) (local.get $payload))
