(module
  (import "host" "realloc" (func $realloc (param i32 i32 i32 i32) (result i32)))
  (import "host" "compare" (func $compare (param i32 i32) (result i32)))
  (memory 1)
  ;; Object: first and last entries. Entry: next, key, tag, padding, f64 payload.
  (func (export "object.new") (result i32) (local $object i32)
    (local.set $object (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 8)))
    (i32.store offset=16 (i32.load (i32.sub (local.get $object) (i32.const 4))) (i32.const 9))
    (i32.store (local.get $object) (i32.const 0))
    (i32.store offset=4 (local.get $object) (i32.const 0))
    (local.get $object))
  (func $get (export "object.get") (param $object i32) (param $key i32) (result i32)
    (local $entry i32)
    (local.set $entry (i32.load (local.get $object)))
    (block $done (loop $entries
      (br_if $done (i32.eqz (local.get $entry)))
      (if (i32.eqz (call $compare (i32.load offset=4 (local.get $entry)) (local.get $key))) (then (return (local.get $entry))))
      (local.set $entry (i32.load (local.get $entry)))
      (br $entries)))
    (i32.const 0))
  (func (export "object.set") (param $object i32) (param $key i32) (param $tag i32) (param $value f64)
    (local $entry i32) (local $last i32)
    (local.set $entry (call $get (local.get $object) (local.get $key)))
    (if (i32.eqz (local.get $entry)) (then
      (local.set $entry (call $realloc (i32.const 0) (i32.const 0) (i32.const 8) (i32.const 24)))
      (i32.store offset=16 (i32.load (i32.sub (local.get $entry) (i32.const 4))) (i32.const 10))
      (i32.store (local.get $entry) (i32.const 0))
      (i32.store offset=4 (local.get $entry) (local.get $key))
      (local.set $last (i32.load offset=4 (local.get $object)))
      (if (local.get $last)
        (then (i32.store (local.get $last) (local.get $entry)))
        (else (i32.store (local.get $object) (local.get $entry))))
      (i32.store offset=4 (local.get $object) (local.get $entry))))
    (i32.store offset=8 (local.get $entry) (local.get $tag))
    (f64.store offset=16 (local.get $entry) (local.get $value)))
  (func (export "object.delete") (param $object i32) (param $key i32) (result i32)
    (local $entry i32) (local $previous i32)
    (local.set $entry (i32.load (local.get $object)))
    (block $done (loop $entries
      (br_if $done (i32.eqz (local.get $entry)))
      (if (i32.eqz (call $compare (i32.load offset=4 (local.get $entry)) (local.get $key))) (then
        (if (local.get $previous)
          (then (i32.store (local.get $previous) (i32.load (local.get $entry))))
          (else (i32.store (local.get $object) (i32.load (local.get $entry)))))
        (if (i32.eq (local.get $entry) (i32.load offset=4 (local.get $object)))
          (then (i32.store offset=4 (local.get $object) (local.get $previous))))
        (br $done)))
      (local.set $previous (local.get $entry))
      (local.set $entry (i32.load (local.get $entry)))
      (br $entries)))
    (i32.const 1))
  ;; Tags: undefined=0, null=1, boolean=2, number=3; reference tags start at 4.
  (func (export "object.value") (param $entry i32) (param $tag i32) (param $optional i32) (result i32 f64)
    (if (i32.eqz (local.get $entry)) (then
      (if (local.get $optional) (then (return (i32.const 0) (f64.const 0))))
      (return (i32.const 1) (f64.const 12))))
    (if (i32.and (local.get $optional) (i32.eqz (i32.load offset=8 (local.get $entry))))
      (then (return (i32.const 0) (f64.const 0))))
    (if (i32.ne (i32.load offset=8 (local.get $entry)) (local.get $tag))
      (then (return (i32.const 1) (f64.const 12))))
    (i32.const 0) (f64.load offset=16 (local.get $entry)))
)
