(module
  (import "host" "realloc" (func $realloc (param i32 i32 i32 i32) (result i32)))
  (import "host" "compare" (func $compare (param i32 i32) (result i32)))
  (import "host" "box" (func $box (param i32 f64) (result i32)))
  (memory 1)
  ;; Object: first, last, frozen flag, unused inline entries, end of inline entries.
  ;; Entry: next, key, tag, padding, f64 payload.
  (func $record (export "object.record") (param $capacity i32) (result i32) (local $object i32) (local $size i32)
    (if (i32.gt_u (local.get $capacity) (i32.const 178956969)) (then unreachable))
    (local.set $size (i32.add (i32.const 24) (i32.mul (local.get $capacity) (i32.const 24))))
    (local.set $object (call $realloc (i32.const 0) (i32.const 0) (i32.const 8) (local.get $size)))
    (i32.store offset=16 (i32.load (i32.sub (local.get $object) (i32.const 4))) (i32.const 9))
    (i32.store (local.get $object) (i32.const 0))
    (i32.store offset=4 (local.get $object) (i32.const 0))
    (i32.store offset=8 (local.get $object) (i32.const 0))
    (i32.store offset=12 (local.get $object) (i32.add (local.get $object) (i32.const 24)))
    (i32.store offset=16 (local.get $object) (i32.add (local.get $object) (local.get $size)))
    (local.get $object))
  (func (export "object.new") (result i32) (call $record (i32.const 0)))

  (func $get (export "object.get") (param $object i32) (param $key i32) (result i32)
    (local $entry i32)
    (local.set $entry (i32.load (local.get $object)))
    (block $done (loop $entries
      (br_if $done (i32.eqz (local.get $entry)))
      (if (i32.eqz (call $compare (i32.load offset=4 (local.get $entry)) (local.get $key))) (then (return (local.get $entry))))
      (local.set $entry (i32.load (local.get $entry)))
      (br $entries)))
    (i32.const 0))
  (func $set (export "object.set") (param $object i32) (param $key i32) (param $tag i32) (param $value f64) (result i32 f64)
    (local $entry i32) (local $last i32)
    (if (i32.load offset=8 (local.get $object)) (then (return (i32.const 1) (f64.const 12))))
    (local.set $entry (call $get (local.get $object) (local.get $key)))
    (if (i32.eqz (local.get $entry)) (then
      (local.set $entry (i32.load offset=12 (local.get $object)))
      (if (i32.lt_u (local.get $entry) (i32.load offset=16 (local.get $object)))
        (then (i32.store offset=12 (local.get $object) (i32.add (local.get $entry) (i32.const 24))))
        (else
          (local.set $entry (call $realloc (i32.const 0) (i32.const 0) (i32.const 8) (i32.const 24)))
          (i32.store offset=16 (i32.load (i32.sub (local.get $entry) (i32.const 4))) (i32.const 10))))
      (i32.store (local.get $entry) (i32.const 0))
      (i32.store offset=4 (local.get $entry) (local.get $key))
      (local.set $last (i32.load offset=4 (local.get $object)))
      (if (local.get $last)
        (then (i32.store (local.get $last) (local.get $entry)))
        (else (i32.store (local.get $object) (local.get $entry))))
      (i32.store offset=4 (local.get $object) (local.get $entry))))
    (i32.store offset=8 (local.get $entry) (local.get $tag))
    (f64.store offset=16 (local.get $entry) (local.get $value))
    (i32.const 0) (f64.const 0))
  (func (export "object.dynamic") (param $entry i32) (result i32)
    (if (i32.eqz (local.get $entry)) (then (return (call $box (i32.const 0) (f64.const 0)))))
    (call $box (i32.load offset=8 (local.get $entry)) (f64.load offset=16 (local.get $entry))))
  ;; Tags: undefined=0, null=1, boolean=2, number=3; reference tags start at 4.
  (func (export "object.value") (param $entry i32) (param $tag i32) (param $optional i32) (result i32 f64)
    (if (i32.eqz (local.get $entry)) (then
      (if (local.get $optional) (then (return (i32.const 0)
        (select (f64.const nan) (f64.const 0) (i32.eq (local.get $tag) (i32.const 3))))))
      (return (i32.const 1) (f64.const 12))))
    (if (i32.and (local.get $optional) (i32.eqz (i32.load offset=8 (local.get $entry))))
      (then (return (i32.const 0)
        (select (f64.const nan) (f64.const 0) (i32.eq (local.get $tag) (i32.const 3))))))
    (if (i32.ne (i32.load offset=8 (local.get $entry)) (local.get $tag))
      (then (return (i32.const 1) (f64.const 12))))
    (i32.const 0) (f64.load offset=16 (local.get $entry)))
)
