  (func (export "fs.directory-options") (param $label i32) (result i32)
    (i32.eqz (call $encoding (local.get $label))))

  (func (export "fs.read-directory") (param $path i32) (param $valid i32) (result i32 f64)
    (local $frame i32) (local $scratch i32) (local $error i32) (local $directory i32)
    (local $reader i32) (local $completion i32) (local $result i32) (local $capacity i32)
    (local $count i32) (local $closed i32) (local $received i32) (local $entry i32)
    (local $data i32) (local $length i32) (local $scalars i32) (local $invalid i32)
    (if (i32.eqz (local.get $valid)) (then (return (i32.const 1) (f64.const 12))))
    (local.set $frame (call $frame-new (i32.const 4)))
    (i32.store offset=12 (local.get $frame) (local.get $path))
    (local.set $scratch (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 24)))
    (i32.store offset=20 (local.get $frame) (local.get $scratch))
    (call $open-path (local.get $path) (local.get $scratch) (local.get $frame) (i32.const 2) (i32.const 1))
    local.set $directory local.set $error
    (if (i32.eqz (local.get $error)) (then
      (call $start-directory (local.get $directory) (local.get $scratch))
      (local.set $reader (i32.load (local.get $scratch)))
      (local.set $completion (i32.load offset=4 (local.get $scratch)))
      (local.set $capacity (i32.const 392))
      (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (local.get $capacity)))
      (i32.store offset=16 (i32.load (i32.sub (local.get $result) (i32.const 4))) (i32.const 2))
      (i32.store (local.get $result) (i32.add (local.get $result) (i32.const 8)))
      (i32.store offset=4 (local.get $result) (i32.const 0))
      (i32.store offset=16 (local.get $frame) (local.get $result))
      (block $done (loop $entries
        (call $read-directory-transfer (local.get $reader) (local.get $scratch) (i32.const 1))
        local.set $closed local.set $received
        (if (local.get $received) (then
          (local.set $data (i32.load offset=16 (local.get $scratch)))
          (local.set $length (i32.load offset=20 (local.get $scratch)))
          (block $skip
            (if (i32.eq (local.get $length) (i32.const 1))
              (then (br_if $skip (i32.eq (i32.load8_u (local.get $data)) (i32.const 46)))))
            (if (i32.eq (local.get $length) (i32.const 2))
              (then (br_if $skip (i32.eq (i32.load16_u align=1 (local.get $data)) (i32.const 0x2e2e)))))
            (call $scan (local.get $data) (local.get $length) (i32.const 0))
            local.set $invalid local.set $scalars drop
            (if (i32.ne (local.get $invalid) (i32.const -1)) (then (local.set $error (i32.const 9)) (br $done)))
            (if (i32.gt_u (i32.add (i32.mul (local.get $count) (i32.const 12)) (i32.const 20)) (local.get $capacity)) (then
              (if (i32.gt_u (local.get $capacity) (i32.const 2147483647))
                (then (local.set $error (i32.const 8)) (br $done)))
              (local.set $result (call $realloc (local.get $result) (local.get $capacity) (i32.const 4)
                (i32.mul (local.get $capacity) (i32.const 2))))
              (local.set $capacity (i32.mul (local.get $capacity) (i32.const 2)))
              (i32.store offset=16 (i32.load (i32.sub (local.get $result) (i32.const 4))) (i32.const 2))
              (i32.store (local.get $result) (i32.add (local.get $result) (i32.const 8)))
              (i32.store offset=16 (local.get $frame) (local.get $result))))
            (local.set $entry (i32.add (i32.add (local.get $result) (i32.const 8)) (i32.mul (local.get $count) (i32.const 12))))
            (i32.store (local.get $entry) (local.get $data))
            (i32.store offset=4 (local.get $entry) (local.get $length))
            (i32.store offset=8 (local.get $entry) (local.get $scalars))
            (local.set $count (i32.add (local.get $count) (i32.const 1)))
            (i32.store offset=4 (local.get $result) (local.get $count)))))
        (br_if $done (local.get $closed))
        (br $entries)))
      (call $drop-entries (local.get $reader))
      (if (call $await (local.get $completion) (local.get $scratch)) (then unreachable))
      (call $drop-future (local.get $completion))
      (call $drop-descriptor (local.get $directory))
      (if (i32.load8_u (local.get $scratch))
        (then (local.set $error (i32.add (i32.load8_u offset=4 (local.get $scratch)) (i32.const 1)))))))
    (call $frame-drop (local.get $frame))
    (i32.ne (local.get $error) (i32.const 0))
    (f64.convert_i32_u (if (result i32) (local.get $error) (then (local.get $error)) (else (local.get $result)))))
