  (import "wasi:filesystem/types@0.3.0" (instance $fs-types
    (export "descriptor" (type $descriptor (sub resource)))
    (type $borrow (borrow $descriptor))
    (type $own (own $descriptor))
    (type $error-base (variant
      (case "access") (case "already") (case "bad-descriptor") (case "busy")
      (case "deadlock") (case "quota") (case "exist") (case "file-too-large")
      (case "illegal-byte-sequence") (case "in-progress") (case "interrupted")
      (case "invalid") (case "io") (case "is-directory") (case "loop")
      (case "too-many-links") (case "message-size") (case "name-too-long")
      (case "no-device") (case "no-entry") (case "no-lock")
      (case "insufficient-memory") (case "insufficient-space") (case "not-directory")
      (case "not-empty") (case "not-recoverable") (case "unsupported") (case "no-tty")
      (case "no-such-device") (case "overflow") (case "not-permitted") (case "pipe")
      (case "read-only") (case "invalid-seek") (case "text-file-busy")
      (case "cross-device") (case "other" (option string))))
    (export "error-code" (type $error (eq $error-base)))
    (type $bytes (stream u8))
    (type $completion (future (result (error $error))))
    (type $path-flags-base (flags "symlink-follow"))
    (export "path-flags" (type $path-flags (eq $path-flags-base)))
    (type $open-flags-base (flags "create" "directory" "exclusive" "truncate"))
    (export "open-flags" (type $open-flags (eq $open-flags-base)))
    (type $descriptor-flags-base (flags "read" "write" "file-integrity-sync" "data-integrity-sync" "requested-write-sync" "mutate-directory"))
    (export "descriptor-flags" (type $descriptor-flags (eq $descriptor-flags-base)))
    (export "[method]descriptor.open-at" (func async
      (param "self" $borrow) (param "path-flags" $path-flags) (param "path" string)
      (param "open-flags" $open-flags) (param "flags" $descriptor-flags)
      (result (result $own (error $error)))))
    (export "[method]descriptor.read-via-stream" (func
      (param "self" $borrow) (param "offset" u64) (result (tuple $bytes $completion))))
    (export "[method]descriptor.write-via-stream" (func
      (param "self" $borrow) (param "data" $bytes) (param "offset" u64) (result $completion)))))
  (alias export $fs-types "descriptor" (type $fs-descriptor))
  (alias export $fs-types "error-code" (type $fs-error))
  (import "wasi:filesystem/preopens@0.3.0" (instance $fs-preopens
    (alias outer 1 $fs-descriptor (type $outer-descriptor))
    (export "descriptor" (type $descriptor (eq $outer-descriptor)))
    (export "get-directories" (func (result (list (tuple (own $descriptor) string)))))))
  (type $fs-completion (future (result (error $fs-error))))
  (type $fs-bytes (stream u8))
