  (func $option-label (param $entry i32) (param $default i32) (result i32)
    (local $tag i32)
    (local.set $tag (i32.load offset=8 (local.get $entry)))
    (if (i32.and (local.get $default) (i32.le_u (local.get $tag) (i32.const 1))) (then (return (i32.const 0))))
    (if (i32.eq (local.get $tag) (i32.const 4))
      (then (return (i32.trunc_f64_u (f64.load offset=16 (local.get $entry))))))
    (i32.const -1))
  (func $file-object-options (param $object i32) (result i32 i32 i32)
    (local $entry i32) (local $key i32) (local $encoding i32) (local $flag i32) (local $valid i32)
    (local.set $valid (i32.const 1))
    (local.set $entry (i32.load (local.get $object)))
    (block $done (loop $fields
      (br_if $done (i32.eqz (local.get $entry)))
      (local.set $key (i32.load offset=4 (local.get $entry)))
      (if (i32.eqz (call $compare (local.get $key) (i32.const __KEY_encoding__)))
        (then (local.set $encoding (call $option-label (local.get $entry) (i32.const 1))))
        (else (if (i32.eqz (call $compare (local.get $key) (i32.const __KEY_flag__)))
          (then (local.set $flag (call $option-label (local.get $entry) (i32.const 0))))
          (else (local.set $valid (i32.const 0))))))
      (local.set $entry (i32.load (local.get $entry)))
      (br $fields)))
    (local.get $encoding) (local.get $flag) (local.get $valid))
  (func (export "fs.read-object-options") (param $object i32) (result i32)
    (call $read-options (call $file-object-options (local.get $object))))
  (func (export "fs.write-object-options") (param $object i32) (param $binary i32) (result i32)
    (local $encoding i32) (local $flag i32) (local $valid i32)
    (call $file-object-options (local.get $object))
    local.set $valid local.set $flag local.set $encoding
    (i32.and (local.get $valid) (call $write-options (local.get $encoding) (local.get $flag) (local.get $binary))))
  ;; Operation 0 validates stat, 1 directory listing; mutations reject object options.
  (func (export "fs.metadata-object-options") (param $object i32) (param $operation i32) (result i32)
    (local $entry i32) (local $key i32) (local $expected i32)
    (if (i32.gt_u (local.get $operation) (i32.const 1)) (then (return (i32.const 0))))
    (local.set $entry (i32.load (local.get $object)))
    (block $done (loop $fields
      (br_if $done (i32.eqz (local.get $entry)))
      (local.set $key (i32.load offset=4 (local.get $entry)))
      (block $next
        (if (local.get $operation) (then
          (if (i32.eqz (call $compare (local.get $key) (i32.const __KEY_encoding__))) (then
            (if (call $encoding (call $option-label (local.get $entry) (i32.const 1))) (then (return (i32.const 0))))
            (br $next)))
          (if (i32.and (i32.ne (call $compare (local.get $key) (i32.const __KEY_recursive__)) (i32.const 0))
              (i32.ne (call $compare (local.get $key) (i32.const __KEY_withFileTypes__)) (i32.const 0)))
            (then (return (i32.const 0))))
          (local.set $expected (i32.const 0)))
        (else
          (if (i32.eqz (call $compare (local.get $key) (i32.const __KEY_bigint__)))
            (then (local.set $expected (i32.const 0)))
            (else (if (i32.eqz (call $compare (local.get $key) (i32.const __KEY_throwIfNoEntry__)))
              (then (local.set $expected (i32.const 1)))
              (else (return (i32.const 0))))))))
        (if (i32.ne (i32.load offset=8 (local.get $entry)) (i32.const 2)) (then (return (i32.const 0))))
        (if (f64.ne (f64.load offset=16 (local.get $entry)) (f64.convert_i32_u (local.get $expected))) (then (return (i32.const 0)))))
      (local.set $entry (i32.load (local.get $entry)))
      (br $fields)))
    (i32.const 1))
