  ;; Encoding: 0 UTF-8, 1 raw bytes, -1 unsupported. Zero means the default.
  (func $encoding (param $label i32) (result i32)
    (local $length i32) (local $data i32) (local $index i32) (local $byte i32) (local $word i64)
    (if (i32.eqz (local.get $label)) (then (return (i32.const 0))))
    (if (i32.eq (local.get $label) (i32.const -1)) (then (return (i32.const -1))))
    (local.set $length (i32.load offset=4 (local.get $label)))
    (if (i32.or (i32.lt_u (local.get $length) (i32.const 4)) (i32.gt_u (local.get $length) (i32.const 6)))
      (then (return (i32.const -1))))
    (local.set $data (i32.load (local.get $label)))
    (loop $bytes
      (local.set $byte (i32.load8_u (i32.add (local.get $data) (local.get $index))))
      (if (i32.and (i32.ge_u (local.get $byte) (i32.const 65)) (i32.le_u (local.get $byte) (i32.const 90)))
        (then (local.set $byte (i32.add (local.get $byte) (i32.const 32)))))
      (local.set $word (i64.or (local.get $word) (i64.shl (i64.extend_i32_u (local.get $byte)) (i64.extend_i32_u (i32.mul (local.get $index) (i32.const 8))))))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br_if $bytes (i32.lt_u (local.get $index) (local.get $length))))
    (if (i32.or
      (i32.and (i32.eq (local.get $length) (i32.const 4)) (i64.eq (local.get $word) (i64.const 0x38667475)))
      (i32.and (i32.eq (local.get $length) (i32.const 5)) (i64.eq (local.get $word) (i64.const 0x382d667475))))
      (then (return (i32.const 0))))
    (if (i64.eq (local.get $word) (i64.const 0x7972616e6962)) (then (return (i32.const 1))))
    (i32.const -1))
  (func $valid-flag (param $flag i32) (param $expected i32) (result i32)
    (if (i32.eq (local.get $flag) (i32.const -1)) (then (return (i32.const 0))))
    (if (local.get $flag)
      (then
        (if (i32.ne (i32.load offset=4 (local.get $flag)) (i32.const 1)) (then (return (i32.const 0))))
        (if (i32.ne (i32.load8_u (i32.load (local.get $flag))) (local.get $expected)) (then (return (i32.const 0))))))
    (i32.const 1))
  (func (export "fs.write-options") (param $label i32) (param $flag i32) (param $binary i32) (result i32)
    (local $encoding i32)
    (if (i32.eqz (call $valid-flag (local.get $flag) (i32.const 119))) (then (return (i32.const 0))))
    (local.set $encoding (call $encoding (local.get $label)))
    (i32.or (i32.eqz (local.get $encoding))
      (i32.and (local.get $binary) (i32.eq (local.get $encoding) (i32.const 1)))))
  ;; Read mode: -1 invalid, 0 bytes, 1 text. An omitted encoding returns bytes.
  (func (export "fs.read-options") (param $label i32) (param $flag i32) (param $valid i32) (result i32)
    (local $encoding i32)
    (if (i32.eqz (i32.and (local.get $valid) (call $valid-flag (local.get $flag) (i32.const 114))))
      (then (return (i32.const -1))))
    (if (i32.eqz (local.get $label)) (then (return (i32.const 0))))
    (local.set $encoding (call $encoding (local.get $label)))
    (if (i32.eq (local.get $encoding) (i32.const -1)) (then (return (i32.const -1))))
    (i32.eqz (local.get $encoding)))
