  (func (export "fs.read") (param $path i32) (param $mode i32) (result i32 f64)
    (local $frame i32) (local $scratch i32) (local $error i32) (local $file i32)
    (local $reader i32) (local $completion i32) (local $data i32)
    (local $length i32)
    (local $result i32) (local $scalars i32) (local $invalid i32)
    (if (i32.eq (local.get $mode) (i32.const -1)) (then (return (i32.const 1) (f64.const 12))))
    (local.set $frame (call $frame-new (i32.const 4)))
    (i32.store offset=12 (local.get $frame) (local.get $path))
    (local.set $scratch (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 24)))
    (i32.store offset=20 (local.get $frame) (local.get $scratch))
    (call $open-path (local.get $path) (local.get $scratch) (local.get $frame) (i32.const 0) (i32.const 1))
    local.set $file local.set $error
    (if (i32.eqz (local.get $error))
      (then
        (call $start-read (local.get $file) (i64.const 0) (local.get $scratch))
        (local.set $reader (i32.load (local.get $scratch)))
        (local.set $completion (i32.load offset=4 (local.get $scratch)))
        (call $read-buffered (local.get $reader) (i32.const -1))
        local.set $length local.set $data local.set $error
        (local.set $error (i32.mul (local.get $error) (i32.const 8)))
        (i32.store offset=16 (local.get $frame) (local.get $data))
        (call $drop-reader (local.get $reader))
        (if (call $await (local.get $completion) (local.get $scratch)) (then unreachable))
        (call $drop-future (local.get $completion))
        (call $drop-descriptor (local.get $file))
        (if (i32.load8_u (local.get $scratch))
          (then (local.set $error (i32.add (i32.load8_u offset=4 (local.get $scratch)) (i32.const 1)))))
        (if (i32.and (i32.eqz (local.get $error)) (local.get $mode))
          (then
            (call $scan (local.get $data) (local.get $length) (i32.const 0))
            local.set $invalid local.set $scalars drop
            (if (i32.ne (local.get $invalid) (i32.const -1)) (then (local.set $error (i32.const 9))))))))
    (if (i32.eqz (local.get $error))
      (then
        (if (local.get $mode)
          (then
            (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 16)))
            (i32.store offset=16 (i32.load (i32.sub (local.get $result) (i32.const 4))) (i32.const 1))
            (i32.store (local.get $result) (local.get $data))
            (i32.store offset=4 (local.get $result) (local.get $length))
            (i32.store offset=8 (local.get $result) (local.get $scalars))
            (i32.store offset=12 (local.get $result) (i32.const 0)))
          (else (local.set $result (call $bytes-lift (local.get $data) (local.get $length)))))))
    (call $frame-drop (local.get $frame))
    (i32.ne (local.get $error) (i32.const 0))
    (f64.convert_i32_u (if (result i32) (local.get $error) (then (local.get $error)) (else (local.get $result)))))
