  (func (export "fs.read") (param $path i32) (param $mode i32) (result i32 f64)
    (local $frame i32) (local $scratch i32) (local $error i32) (local $file i32)
    (local $reader i32) (local $completion i32) (local $data i32) (local $capacity i32)
    (local $length i32) (local $count i32) (local $closed i32) (local $requested i32)
    (local $result i32) (local $scalars i32) (local $invalid i32)
    (if (i32.eq (local.get $mode) (i32.const -1)) (then (return (i32.const 1) (f64.const 12))))
    (local.set $frame (call $frame-new (i32.const 4)))
    (i32.store offset=12 (local.get $frame) (local.get $path))
    (local.set $scratch (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 24)))
    (i32.store offset=20 (local.get $frame) (local.get $scratch))
    (call $open-path (local.get $path) (local.get $scratch) (local.get $frame) (i32.const 0) (i32.const 1))
    local.set $file local.set $error
    (if (i32.eqz (local.get $error))
      (then
        (call $start-read (local.get $file) (i64.const 0) (local.get $scratch))
        (local.set $reader (i32.load (local.get $scratch)))
        (local.set $completion (i32.load offset=4 (local.get $scratch)))
        (local.set $capacity (i32.const 8192))
        (local.set $data (call $realloc (i32.const 0) (i32.const 0) (i32.const 1) (local.get $capacity)))
        (i32.store offset=16 (local.get $frame) (local.get $data))
        (block $done (loop $transfer
          (if (i32.eq (local.get $length) (local.get $capacity))
            (then
              (if (i32.gt_u (local.get $capacity) (i32.const 2147483647))
                (then (local.set $error (i32.const 8)) (br $done)))
              (local.set $data (call $realloc (local.get $data) (local.get $capacity) (i32.const 1)
                (i32.mul (local.get $capacity) (i32.const 2))))
              (local.set $capacity (i32.mul (local.get $capacity) (i32.const 2)))
              (i32.store offset=16 (local.get $frame) (local.get $data))))
          (local.set $requested (i32.sub (local.get $capacity) (local.get $length)))
          (if (i32.gt_u (local.get $requested) (i32.const 8192)) (then (local.set $requested (i32.const 8192))))
          (call $read-transfer (local.get $reader) (i32.add (local.get $data) (local.get $length)) (local.get $requested))
          local.set $closed local.set $count
          (local.set $length (i32.add (local.get $length) (local.get $count)))
          (br_if $done (local.get $closed))
          (br $transfer)))
        (call $drop-reader (local.get $reader))
        (if (call $await (local.get $completion) (local.get $scratch)) (then unreachable))
        (call $drop-future (local.get $completion))
        (call $drop-descriptor (local.get $file))
        (if (i32.load8_u (local.get $scratch))
          (then (local.set $error (i32.add (i32.load8_u offset=4 (local.get $scratch)) (i32.const 1)))))
        (if (i32.and (i32.eqz (local.get $error)) (local.get $mode))
          (then
            (call $scan (local.get $data) (local.get $length) (i32.const 0))
            local.set $invalid local.set $scalars drop
            (if (i32.ne (local.get $invalid) (i32.const -1)) (then (local.set $error (i32.const 9))))))))
    (if (i32.eqz (local.get $error))
      (then
        (local.set $data (call $realloc (local.get $data) (local.get $capacity) (i32.const 1)
          (if (result i32) (local.get $length) (then (local.get $length)) (else (i32.const 1)))))
        (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 16)))
        (i32.store offset=16 (i32.load (i32.sub (local.get $result) (i32.const 4)))
          (if (result i32) (local.get $mode) (then (i32.const 1)) (else (i32.const 7))))
        (i32.store (local.get $result) (local.get $data))
        (i32.store offset=4 (local.get $result) (local.get $length))
        (i32.store offset=8 (local.get $result)
          (if (result i32) (local.get $mode) (then (local.get $scalars)) (else (local.get $data))))
        (i32.store offset=12 (local.get $result) (i32.const 0))))
    (call $frame-drop (local.get $frame))
    (i32.ne (local.get $error) (i32.const 0))
    (f64.convert_i32_u (if (result i32) (local.get $error) (then (local.get $error)) (else (local.get $result)))))
