  (func (export "fs.write") (param $path i32) (param $data i32) (param $valid i32) (result i32 f64)
    (local $frame i32) (local $scratch i32) (local $error i32) (local $file i32)
    (local $pair i64) (local $writer i32) (local $completion i32) (local $short i32)
    (if (i32.eqz (local.get $valid)) (then (return (i32.const 1) (f64.const 12))))
    (local.set $frame (call $frame-new (i32.const 4)))
    (i32.store offset=12 (local.get $frame) (local.get $path))
    (i32.store offset=16 (local.get $frame) (local.get $data))
    (local.set $scratch (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 24)))
    (i32.store offset=20 (local.get $frame) (local.get $scratch))
    (call $open-file (local.get $path) (local.get $scratch) (local.get $frame) (i32.const 1))
    local.set $file local.set $error
    (if (i32.eqz (local.get $error))
      (then
        (local.set $pair (call $new))
        (local.set $writer (i32.wrap_i64 (i64.shr_u (local.get $pair) (i64.const 32))))
        (local.set $completion (call $start-write (local.get $file) (i32.wrap_i64 (local.get $pair)) (i64.const 0)))
        (local.set $short (i32.ne
          (call $write-buffer (local.get $writer) (i32.load (local.get $data)) (i32.load offset=4 (local.get $data)))
          (i32.load offset=4 (local.get $data))))
        (call $drop-writer (local.get $writer))
        (if (call $await (local.get $completion) (local.get $scratch)) (then unreachable))
        (call $drop-future (local.get $completion))
        (call $drop-descriptor (local.get $file))
        (if (i32.load8_u (local.get $scratch))
          (then (local.set $error (i32.add (i32.load8_u offset=4 (local.get $scratch)) (i32.const 1)))))
        (if (i32.and (local.get $short) (i32.eqz (local.get $error)))
          (then (local.set $error (i32.const 32))))))
    (call $frame-drop (local.get $frame))
    (i32.ne (local.get $error) (i32.const 0)) (f64.convert_i32_u (local.get $error)))
