(module
  (import "heap" "realloc" (func $realloc (param i32 i32 i32 i32) (result i32)))
  (memory 1)
  ;; Decoder: ignore BOM, continued, BOM seen, pending data, pending length.
  ;; Pending bytes include an unfinished scalar or unconsumed input after an error.
  (func (export "decoder.new") (param $label i32) (param $fatal i32) (param $ignore i32) (result i32 f64)
    (local $decoder i32)
    (if (i32.or (i32.eqz (call $valid-label (local.get $label))) (i32.eqz (local.get $fatal)))
      (then (return (i32.const 1) (f64.const 1))))
    (local.set $decoder (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 20)))
    (memory.fill (local.get $decoder) (i32.const 0) (i32.const 20))
    (i32.store offset=16 (i32.load (i32.sub (local.get $decoder) (i32.const 4))) (i32.const 8))
    (i32.store (local.get $decoder) (local.get $ignore))
    (i32.const 0) (f64.convert_i32_u (local.get $decoder)))

  (func (export "decoder.decode") (param $decoder i32) (param $view i32) (param $stream i32) (result i32 f64)
    (local $length i32) (local $pending i32) (local $total i64) (local $data i32)
    (local $prefix i32) (local $scalars i32) (local $error i32) (local $skip i32) (local $result i32)
    (if (i32.eqz (i32.load offset=4 (local.get $decoder))) (then
      (i32.store offset=8 (local.get $decoder) (i32.const 0))
      (i32.store offset=16 (local.get $decoder) (i32.const 0))))
    (i32.store offset=4 (local.get $decoder) (local.get $stream))
    (if (local.get $view) (then (local.set $length (i32.load offset=4 (local.get $view)))))
    (local.set $pending (i32.load offset=16 (local.get $decoder)))
    (local.set $total (i64.add (i64.extend_i32_u (local.get $pending)) (i64.extend_i32_u (local.get $length))))
    (if (i64.gt_u (local.get $total) (i64.const 4294967295)) (then unreachable))
    (local.set $data (call $realloc (i32.const 0) (i32.const 0) (i32.const 1) (i32.wrap_i64 (local.get $total))))
    (memory.copy (local.get $data) (i32.load offset=12 (local.get $decoder)) (local.get $pending))
    (if (local.get $length) (then
      (memory.copy (i32.add (local.get $data) (local.get $pending)) (i32.load (local.get $view)) (local.get $length))))
    (call $scan (local.get $data) (i32.wrap_i64 (local.get $total)) (local.get $stream))
    local.set $error
    local.set $scalars
    local.set $prefix
    (if (i32.ne (local.get $error) (i32.const -1)) (then
      (i32.store offset=12 (local.get $decoder) (i32.add (local.get $data) (local.get $error)))
      (i32.store offset=16 (local.get $decoder) (i32.sub (i32.wrap_i64 (local.get $total)) (local.get $error)))
      (return (i32.const 1) (f64.const 2))))
    (i32.store offset=12 (local.get $decoder) (i32.add (local.get $data) (local.get $prefix)))
    (i32.store offset=16 (local.get $decoder) (i32.sub (i32.wrap_i64 (local.get $total)) (local.get $prefix)))
    (if (i32.and (i32.gt_u (local.get $scalars) (i32.const 0)) (i32.eqz (i32.or (i32.load (local.get $decoder)) (i32.load offset=8 (local.get $decoder))))) (then
      (i32.store offset=8 (local.get $decoder) (i32.const 1))
      (if (i32.ge_u (local.get $prefix) (i32.const 3)) (then
        (if (i32.and (i32.eq (i32.load8_u (local.get $data)) (i32.const 239))
          (i32.and (i32.eq (i32.load8_u offset=1 (local.get $data)) (i32.const 187))
            (i32.eq (i32.load8_u offset=2 (local.get $data)) (i32.const 191))))
          (then (local.set $skip (i32.const 3)) (local.set $scalars (i32.sub (local.get $scalars) (i32.const 1)))))))))
    (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 12)))
    (i32.store offset=16 (i32.load (i32.sub (local.get $result) (i32.const 4))) (i32.const 1))
    (i32.store (local.get $result) (i32.add (local.get $data) (local.get $skip)))
    (i32.store offset=4 (local.get $result) (i32.sub (local.get $prefix) (local.get $skip)))
    (i32.store offset=8 (local.get $result) (local.get $scalars))
    (i32.const 0) (f64.convert_i32_u (local.get $result)))

  ;; Returns complete prefix length, scalar count, and the unconsumed offset on
  ;; failure (-1 on success). An invalid continuation is restored for the next call.
  (func $scan (param $data i32) (param $length i32) (param $stream i32) (result i32 i32 i32)
    (local $index i32) (local $scalars i32) (local $lead i32) (local $width i32)
    (local $next i32) (local $byte i32) (local $lower i32) (local $upper i32)
    (block $done (loop $scalar
      (br_if $done (i32.ge_u (local.get $index) (local.get $length)))
      (local.set $lead (i32.load8_u (i32.add (local.get $data) (local.get $index))))
      (local.set $width (i32.const 1))
      (if (i32.ge_u (local.get $lead) (i32.const 128)) (then
        (if (i32.or (i32.lt_u (local.get $lead) (i32.const 194)) (i32.gt_u (local.get $lead) (i32.const 244)))
          (then (return (local.get $index) (local.get $scalars) (i32.add (local.get $index) (i32.const 1)))))
        (local.set $width (i32.const 2))
        (if (i32.ge_u (local.get $lead) (i32.const 224)) (then (local.set $width (i32.const 3))))
        (if (i32.ge_u (local.get $lead) (i32.const 240)) (then (local.set $width (i32.const 4))))))
      (local.set $next (i32.const 1))
      (block $complete (loop $continuation
        (br_if $complete (i32.ge_u (local.get $next) (local.get $width)))
        (if (i32.ge_u (local.get $next) (i32.sub (local.get $length) (local.get $index))) (then
          (if (local.get $stream)
            (then (return (local.get $index) (local.get $scalars) (i32.const -1)))
            (else (return (local.get $index) (local.get $scalars) (local.get $length))))))
        (local.set $byte (i32.load8_u (i32.add (local.get $data) (i32.add (local.get $index) (local.get $next)))))
        (local.set $lower (i32.const 128))
        (local.set $upper (i32.const 191))
        (if (i32.eq (local.get $next) (i32.const 1)) (then
          (if (i32.eq (local.get $lead) (i32.const 224)) (then (local.set $lower (i32.const 160))))
          (if (i32.eq (local.get $lead) (i32.const 237)) (then (local.set $upper (i32.const 159))))
          (if (i32.eq (local.get $lead) (i32.const 240)) (then (local.set $lower (i32.const 144))))
          (if (i32.eq (local.get $lead) (i32.const 244)) (then (local.set $upper (i32.const 143))))))
        (if (i32.or (i32.lt_u (local.get $byte) (local.get $lower)) (i32.gt_u (local.get $byte) (local.get $upper)))
          (then (return (local.get $index) (local.get $scalars) (i32.add (local.get $index) (local.get $next)))))
        (local.set $next (i32.add (local.get $next) (i32.const 1)))
        (br $continuation)))
      (local.set $scalars (i32.add (local.get $scalars) (i32.const 1)))
      (local.set $index (i32.add (local.get $index) (local.get $width)))
      (br $scalar)))
    (local.get $index) (local.get $scalars) (i32.const -1))

  (func $space (param $byte i32) (result i32)
    (i32.or (i32.eq (local.get $byte) (i32.const 32))
      (i32.or (i32.eq (local.get $byte) (i32.const 9))
        (i32.or (i32.eq (local.get $byte) (i32.const 10))
          (i32.or (i32.eq (local.get $byte) (i32.const 12)) (i32.eq (local.get $byte) (i32.const 13)))))))

  (func $valid-label (param $label i32) (result i32)
    (local $data i32) (local $length i32) (local $index i32) (local $byte i32)
    (local $low i64) (local $high i64) (local $tail i64)
    (if (i32.eqz (local.get $label)) (then (return (i32.const 1))))
    (local.set $data (i32.load (local.get $label)))
    (local.set $length (i32.load offset=4 (local.get $label)))
    (block $leading-done (loop $leading
      (br_if $leading-done (i32.eqz (local.get $length)))
      (br_if $leading-done (i32.eqz (call $space (i32.load8_u (local.get $data)))))
      (local.set $data (i32.add (local.get $data) (i32.const 1)))
      (local.set $length (i32.sub (local.get $length) (i32.const 1)))
      (br $leading)))
    (block $trailing-done (loop $trailing
      (br_if $trailing-done (i32.eqz (local.get $length)))
      (br_if $trailing-done (i32.eqz (call $space (i32.load8_u (i32.add (local.get $data) (i32.sub (local.get $length) (i32.const 1)))))))
      (local.set $length (i32.sub (local.get $length) (i32.const 1)))
      (br $trailing)))
    (if (i32.gt_u (local.get $length) (i32.const 17)) (then (return (i32.const 0))))
    (block $packed (loop $pack
      (br_if $packed (i32.ge_u (local.get $index) (local.get $length)))
      (local.set $byte (i32.load8_u (i32.add (local.get $data) (local.get $index))))
      (if (i32.and (i32.ge_u (local.get $byte) (i32.const 65)) (i32.le_u (local.get $byte) (i32.const 90)))
        (then (local.set $byte (i32.add (local.get $byte) (i32.const 32)))))
      (if (i32.lt_u (local.get $index) (i32.const 8))
        (then (local.set $low (i64.or (local.get $low) (i64.shl (i64.extend_i32_u (local.get $byte)) (i64.extend_i32_u (i32.mul (local.get $index) (i32.const 8)))))))
        (else (if (i32.lt_u (local.get $index) (i32.const 16))
          (then (local.set $high (i64.or (local.get $high) (i64.shl (i64.extend_i32_u (local.get $byte)) (i64.extend_i32_u (i32.mul (i32.sub (local.get $index) (i32.const 8)) (i32.const 8)))))))
          (else (local.set $tail (i64.extend_i32_u (local.get $byte)))))))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $pack)))
    ;; ASCII-folded, little-endian UTF-8 labels: unicode-1-1-utf-8, unicode11utf8,
    ;; unicode20utf8, utf-8, utf8, x-unicode20utf8. Length is part of each match.
    (if (i32.and (i32.eq (local.get $length) (i32.const 17))
      (i32.and (i64.eq (local.get $low) (i64.const 3271131133926534773))
        (i32.and (i64.eq (local.get $high) (i64.const 3271430225949437233)) (i64.eq (local.get $tail) (i64.const 56)))))
      (then (return (i32.const 1))))
    (if (i32.and (i32.eq (local.get $length) (i32.const 13))
      (i32.and (i64.eq (local.get $low) (i64.const 3559361510078246517))
        (i32.and (i64.eq (local.get $high) (i64.const 242237076785)) (i64.eq (local.get $tail) (i64.const 0)))))
      (then (return (i32.const 1))))
    (if (i32.and (i32.eq (local.get $length) (i32.const 13))
      (i32.and (i64.eq (local.get $low) (i64.const 3631419104116174453))
        (i32.and (i64.eq (local.get $high) (i64.const 242237076784)) (i64.eq (local.get $tail) (i64.const 0)))))
      (then (return (i32.const 1))))
    (if (i32.and (i32.eq (local.get $length) (i32.const 5))
      (i32.and (i64.eq (local.get $low) (i64.const 241279857781))
        (i32.and (i64.eq (local.get $high) (i64.const 0)) (i64.eq (local.get $tail) (i64.const 0)))))
      (then (return (i32.const 1))))
    (if (i32.and (i32.eq (local.get $length) (i32.const 4))
      (i32.and (i64.eq (local.get $low) (i64.const 946238581))
        (i32.and (i64.eq (local.get $high) (i64.const 0)) (i64.eq (local.get $tail) (i64.const 0)))))
      (then (return (i32.const 1))))
    (if (i32.and (i32.eq (local.get $length) (i32.const 15))
      (i32.and (i64.eq (local.get $low) (i64.const 7237112430683565432))
        (i32.and (i64.eq (local.get $high) (i64.const 15875249064129125)) (i64.eq (local.get $tail) (i64.const 0)))))
      (then (return (i32.const 1))))
    (i32.const 0)))
