  (func $fill-bytes (param $data i32) (param $count i32)
    (local $result i32) (local $source i32) (local $length i32)
    (if (i32.eqz (local.get $count)) (then return))
    (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 8)))
    (loop $fill
      (call $bytes (i64.extend_i32_u (local.get $count)) (local.get $result))
      (local.set $source (i32.load (local.get $result)))
      (local.set $length (i32.load offset=4 (local.get $result)))
      ;; A zero or oversized result violates the native API's progress contract.
      (if (i32.or (i32.eqz (local.get $length)) (i32.gt_u (local.get $length) (local.get $count))) (then unreachable))
      (memory.copy (local.get $data) (local.get $source) (local.get $length))
      (drop (call $realloc (local.get $source) (local.get $length) (i32.const 1) (i32.const 0)))
      (local.set $data (i32.add (local.get $data) (local.get $length)))
      (local.set $count (i32.sub (local.get $count) (local.get $length)))
      (br_if $fill (local.get $count)))
    (drop (call $realloc (local.get $result) (i32.const 8) (i32.const 4) (i32.const 0))))

  (func (export "crypto.getRandomValues") (param $view i32) (param $valid i32) (result i32 f64)
    (if (i32.eqz (local.get $valid)) (then (return (i32.const 1) (f64.const 1))))
    (if (i32.gt_u (i32.load offset=4 (local.get $view)) (i32.const 65536)) (then (return (i32.const 1) (f64.const 2))))
    (call $fill-bytes (i32.load (local.get $view)) (i32.load offset=4 (local.get $view)))
    (i32.const 0) (f64.convert_i32_u (local.get $view)))

  (func $hex (param $digit i32) (result i32)
    (i32.add (local.get $digit) (select (i32.const 48) (i32.const 87) (i32.lt_u (local.get $digit) (i32.const 10)))))

  (func (export "crypto.randomUUID") (result i32)
    (local $bytes i32) (local $string i32) (local $cursor i32) (local $index i32) (local $byte i32)
    (local.set $bytes (call $realloc (i32.const 0) (i32.const 0) (i32.const 1) (i32.const 16)))
    (call $fill-bytes (local.get $bytes) (i32.const 16))
    (i32.store8 offset=6 (local.get $bytes) (i32.or (i32.and (i32.load8_u offset=6 (local.get $bytes)) (i32.const 15)) (i32.const 64)))
    (i32.store8 offset=8 (local.get $bytes) (i32.or (i32.and (i32.load8_u offset=8 (local.get $bytes)) (i32.const 63)) (i32.const 128)))
    (local.set $string (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.const 48)))
    (i32.store offset=16 (i32.load (i32.sub (local.get $string) (i32.const 4))) (i32.const 1))
    (local.set $cursor (i32.add (local.get $string) (i32.const 12)))
    (i32.store (local.get $string) (local.get $cursor))
    (i32.store offset=4 (local.get $string) (i32.const 36))
    (i32.store offset=8 (local.get $string) (i32.const 36))
    (loop $digits
      (if (i32.or (i32.or (i32.eq (local.get $index) (i32.const 4)) (i32.eq (local.get $index) (i32.const 6)))
        (i32.or (i32.eq (local.get $index) (i32.const 8)) (i32.eq (local.get $index) (i32.const 10)))) (then
          (i32.store8 (local.get $cursor) (i32.const 45))
          (local.set $cursor (i32.add (local.get $cursor) (i32.const 1)))))
      (local.set $byte (i32.load8_u (i32.add (local.get $bytes) (local.get $index))))
      (i32.store8 (local.get $cursor) (call $hex (i32.shr_u (local.get $byte) (i32.const 4))))
      (i32.store8 offset=1 (local.get $cursor) (call $hex (i32.and (local.get $byte) (i32.const 15))))
      (local.set $cursor (i32.add (local.get $cursor) (i32.const 2)))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br_if $digits (i32.lt_u (local.get $index) (i32.const 16))))
    (drop (call $realloc (local.get $bytes) (i32.const 16) (i32.const 1) (i32.const 0)))
    (local.get $string))
