"""Generate casing-context ranges from Unicode 17 DerivedCoreProperties.txt."""

import argparse
from pathlib import Path


def generate(source: str) -> str:
    assert source.startswith('# DerivedCoreProperties-17.0.0.txt')
    properties = {'Cased': [], 'Case_Ignorable': []}
    for line in source.splitlines():
        fields = line.partition('#')[0].strip().split(';')
        if len(fields) < 2 or fields[1].strip() not in properties:
            continue
        bounds = fields[0].strip().split('..')
        start, end = int(bounds[0], 16), int(bounds[-1], 16)
        ranges = properties[fields[1].strip()]
        if ranges and ranges[-1][1] + 1 == start:
            ranges[-1] = (ranges[-1][0], end)
        else:
            ranges.append((start, end))
    output = [
        '//! Generated by scripts/generate_unicode_casing.py; Unicode License V3 in unicode-license.txt.',
        '//! Source: https://www.unicode.org/Public/17.0.0/ucd/DerivedCoreProperties.txt',
        '',
    ]
    for name, ranges in properties.items():
        output.append(f'pub(super) const {name.upper()}: &[(u32, u32)] = &[')
        output.extend(f'    (0x{start:X}, 0x{end:X}),' for start, end in ranges)
        output.extend(['];', ''])
    return '\n'.join(output)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    args.output.write_text(generate(args.source.read_text(encoding='utf-8')), encoding='utf-8')
