  (func (export "stats.lift") (param $size f64) (param $mtime f64) (param $kind i32) (result i32)
    (local $stats i32)
    (if (i32.gt_u (local.get $kind) (i32.const 7)) (then unreachable))
    (local.set $stats (call $realloc (i32.const 0) (i32.const 0) (i32.const 8) (i32.const 24)))
    (f64.store (local.get $stats) (local.get $size))
    (f64.store offset=8 (local.get $stats) (local.get $mtime))
    (i32.store offset=16 (local.get $stats) (local.get $kind))
    (local.get $stats))
  (func (export "strings.lift") (param $data i32) (param $count i32) (result i32)
    (local $array i32) (local $index i32) (local $source i32) (local $target i32)
    (local $scalars i32) (local $invalid i32)
    (if (i32.gt_u (local.get $count) (i32.const 357913940)) (then unreachable))
    (local.set $array (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.add (i32.const 8) (i32.mul (local.get $count) (i32.const 12)))))
    (i32.store offset=16 (i32.load (i32.sub (local.get $array) (i32.const 4))) (i32.const 2))
    (i32.store (local.get $array) (i32.add (local.get $array) (i32.const 8)))
    (i32.store offset=4 (local.get $array) (local.get $count))
    (block $done (loop $entries
      (br_if $done (i32.eq (local.get $index) (local.get $count)))
      (local.set $source (i32.add (local.get $data) (i32.mul (local.get $index) (i32.const 8))))
      (local.set $target (i32.add (i32.add (local.get $array) (i32.const 8)) (i32.mul (local.get $index) (i32.const 12))))
      (call $scan (i32.load (local.get $source)) (i32.load offset=4 (local.get $source)) (i32.const 0))
      local.set $invalid local.set $scalars drop
      (if (i32.ne (local.get $invalid) (i32.const -1)) (then unreachable))
      (i32.store (local.get $target) (i32.load (local.get $source)))
      (i32.store offset=4 (local.get $target) (i32.load offset=4 (local.get $source)))
      (i32.store offset=8 (local.get $target) (local.get $scalars))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $entries)))
    (local.get $array))
  (func (export "strings.lower") (param $array i32) (result i32)
    (local $data i32) (local $count i32) (local $result i32) (local $index i32)
    (local $source i32) (local $target i32)
    (local.set $data (i32.load (local.get $array)))
    (local.set $count (i32.load offset=4 (local.get $array)))
    (if (i32.gt_u (local.get $count) (i32.const 536870910)) (then unreachable))
    (local.set $result (call $realloc (i32.const 0) (i32.const 0) (i32.const 4) (i32.add (i32.const 8) (i32.mul (local.get $count) (i32.const 8)))))
    (i32.store (local.get $result) (i32.add (local.get $result) (i32.const 8)))
    (i32.store offset=4 (local.get $result) (local.get $count))
    (block $done (loop $entries
      (br_if $done (i32.eq (local.get $index) (local.get $count)))
      (local.set $source (i32.add (local.get $data) (i32.mul (local.get $index) (i32.const 12))))
      (local.set $target (i32.add (i32.add (local.get $result) (i32.const 8)) (i32.mul (local.get $index) (i32.const 8))))
      (i32.store (local.get $target) (i32.load (local.get $source)))
      (i32.store offset=4 (local.get $target) (i32.load offset=4 (local.get $source)))
      (local.set $index (i32.add (local.get $index) (i32.const 1)))
      (br $entries)))
    (local.get $result))
